"""Inline Kubernetes manifest generators for QS block types.

Each generator returns a dict of {filename: template_string} where the
template strings use Helm Go-template syntax ({{ .Values.xxx }}) so the
output chart supports helm install --set overrides.

Infrastructure blocks (ai-platform-foundation, gpu-compute) return only
prerequisite strings for NOTES.txt — they are not deployed by the QS chart.
"""


def _camel(name: str) -> str:
    """Convert kebab-case to camelCase for Helm values keys."""
    parts = name.split('-')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


# ── Prerequisites (infrastructure blocks) ───────────────────────────────────


def ai_platform_foundation_prereqs(config: dict) -> list[str]:
    dsc = config.get('dsc', {})
    managed = [k for k, v in dsc.items() if v == 'Managed']
    channel = config.get('channel', 'fast')
    return [
        f'OpenShift AI operator installed (channel: {channel})',
        'OpenShift Serverless operator installed',
        'Red Hat OpenShift Service Mesh operator installed',
        'DataScienceCluster configured with: ' + (', '.join(managed) or 'kserve, dashboard'),
    ]


def gpu_compute_prereqs(config: dict) -> list[str]:
    channel = config.get('channel', 'v24.9')
    mig = config.get('mig_strategy', 'none')
    return [
        f'NVIDIA GPU Operator installed (channel: {channel})',
        'Node Feature Discovery operator installed',
        f'ClusterPolicy configured (mig_strategy: {mig})',
        'GPU node(s) available with nvidia.com/gpu resource',
    ]


# ── Model Serving ────────────────────────────────────────────────────────────


def model_serving_templates(block_name: str, config: dict) -> dict[str, str]:
    """Generate ServingRuntime + InferenceService for a model-serving block."""
    runtime = config.get('runtime', 'vllm')
    if runtime == 'vllm':
        sr = _vllm_serving_runtime(block_name, config)
    else:
        sr = _custom_serving_runtime(block_name, config)
    return {
        'servingruntime.yaml': sr,
        'inferenceservice.yaml': _inference_service(block_name, config),
    }


def _vllm_serving_runtime(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    vllm_args = config.get('vllm_args', {})
    extra_args = ''.join(
        f'\n        - --{k.replace("_", "-")}={v}'
        for k, v in vllm_args.items()
    )
    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  supportedModelFormats:
    - name: vllm
      version: "1"
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: {{{{ .Values.{key}.image }}}}
      args:
        - --model=/mnt/models
        - --served-model-name={{{{ .Values.{key}.model }}}}{extra_args}
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
          nvidia.com/gpu: "1"
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
          nvidia.com/gpu: "1"
"""


def _custom_serving_runtime(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  supportedModelFormats:
    - name: {block_name}
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: {{{{ .Values.{key}.image }}}}
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
"""


def _inference_service(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    runtime = config.get('runtime', 'vllm')
    model_format = 'vllm' if runtime == 'vllm' else block_name
    gpu = config.get('gpu', False)
    replicas = config.get('replicas', {})
    min_r = replicas.get('min', 0) if isinstance(replicas, dict) else 0
    max_r = replicas.get('max', 1) if isinstance(replicas, dict) else 1
    storage = config.get('storage', {})
    storage_type = storage.get('type', 'oci')

    if storage_type == 'oci':
        storage_line = f'      storageUri: {{{{ .Values.{key}.storageUri }}}}'
    else:
        # S3 — references the MinIO data connection secret by name
        storage_line = (
            f'      storage:\n'
            f'        key: {storage.get("connection", "model-storage-data-connection")}\n'
            f'        path: {{{{ .Values.{key}.modelPath }}}}'
        )

    toleration = (
        '    tolerations:\n'
        '      - key: nvidia.com/gpu\n'
        '        operator: Exists\n'
        '        effect: NoSchedule\n'
    ) if gpu else ''

    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  predictor:
    minReplicas: {min_r}
    maxReplicas: {max_r}
{toleration}    model:
      modelFormat:
        name: {model_format}
      runtime: {block_name}
{storage_line}
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
"""


# ── Object Storage (MinIO) ────────────────────────────────────────────────────


def object_storage_templates(block_name: str, config: dict) -> dict[str, str]:
    key = _camel(block_name)
    init_models = config.get('init_models', [])
    models_csv = ','.join(init_models)

    pvc = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {block_name}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{{{ .Values.{key}.storage }}}}
"""

    deployment = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {block_name}
  template:
    metadata:
      labels:
        app: {block_name}
    spec:
      initContainers:
        - name: download-models
          image: quay.io/rgeada/llm_downloader:latest
          env:
            - name: MODELS_PATH
              value: /mnt/models/huggingface
            - name: MODEL_IDS
              value: {models_csv!r}
          volumeMounts:
            - name: model-pvc
              mountPath: /mnt/models
      containers:
        - name: minio
          image: {{{{ .Values.{key}.image }}}}
          args:
            - server
            - /models
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: model-pvc
              mountPath: /models
      volumes:
        - name: model-pvc
          persistentVolumeClaim:
            claimName: {block_name}-pvc
"""

    service = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: Service
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  selector:
    app: {block_name}
  ports:
    - name: api
      port: 9000
      targetPort: 9000
"""

    # MinIO pod credentials secret
    credentials = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if .Values.secrets.minioAccessKey }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{{{ .Values.secrets.minioAccessKey | quote }}}}
  AWS_SECRET_ACCESS_KEY: {{{{ .Values.secrets.minioSecretKey | quote }}}}
{{{{- end }}}}
"""

    # RHOAI data connection secret (for KServe storage key)
    data_connection = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if .Values.secrets.minioAccessKey }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-data-connection
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{{{ .Values.secrets.minioAccessKey | quote }}}}
  AWS_SECRET_ACCESS_KEY: {{{{ .Values.secrets.minioSecretKey | quote }}}}
  AWS_S3_ENDPOINT: http://{block_name}:9000
  AWS_S3_BUCKET: huggingface
  AWS_DEFAULT_REGION: us-east-1
{{{{- end }}}}
"""

    return {
        'pvc.yaml': pvc,
        'deployment.yaml': deployment,
        'service.yaml': service,
        'credentials.yaml': credentials,
        'data-connection.yaml': data_connection,
    }


# ── Guardrails Orchestrator ───────────────────────────────────────────────────


def guardrails_orchestrator_templates(block_name: str, config: dict) -> dict[str, str]:
    detectors = config.get('detectors', {})
    detector_lines = '\n'.join(
        f'      {name}:\n        hostname: {det.get("endpoint", f"{name}-predictor")}\n        port: {det.get("port", 8000)}'
        for name, det in detectors.items()
    )

    chunker = config.get('chunker') or {}
    chunker_section = (
        f'    chunkers:\n'
        f'      sentence:\n'
        f'        hostname: {chunker.get("endpoint", "chunker-service")}\n'
        f'        port: {chunker.get("port", 8085)}\n'
    ) if chunker else ''

    lang_det = config.get('language_detector') or {}
    lang_section = (
        f'      language_detection:\n'
        f'        hostname: {lang_det.get("endpoint", "lingua-detector")}\n'
        f'        port: {lang_det.get("port", 8080)}\n'
    ) if lang_det else ''

    llm_endpoint = (config.get('llm') or {}).get('endpoint', 'llm-predictor')
    enable_built_in = str(config.get('enable_built_in_detectors', True)).lower()
    enable_gateway = str(config.get('enable_guardrails_gateway', False)).lower()
    otel_proto = config.get('otel_protocol', 'grpc')

    orchestrator = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: {block_name}
spec:
  enableBuiltInDetectors: {enable_built_in}
  enableGuardrailsGateway: {enable_gateway}
  orchestratorConfig: {block_name}-config
  otelExporter:
    otlpProtocol: {otel_proto}
  replicas: 1
"""

    configmap = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: ConfigMap
metadata:
  name: {block_name}-config
data:
  config.yaml: |
{chunker_section}    openai:
      service:
        hostname: {llm_endpoint}
    detectors:
{detector_lines}
{lang_section}"""

    return {
        'orchestrator.yaml': orchestrator,
        'configmap.yaml': configmap,
    }


# ── Values builder ───────────────────────────────────────────────────────────


def build_values(spec, secret_keys: list[str]) -> str:
    """Build values.yaml content from the ApplicationSpec.

    Returns a YAML string with documentation comments. Secrets are listed
    as empty-string placeholders — fill in before helm install or use
    scripts/create-secrets.sh.
    """
    lines = [
        '# Generated by quickpat compose -- do not edit',
        '# Override any value with: helm install <name> ./chart --set key=value',
        '',
        '# ── Secrets ──────────────────────────────────────────────────────────',
        '# Fill these in before helm install, or use scripts/create-secrets.sh',
        'secrets:',
    ]
    for key in secret_keys:
        lines.append(f'  {key}: ""')

    for block_name, block in spec.blocks.items():
        key = _camel(block_name)
        btype = block.block_type
        cfg = block.config or {}

        if btype in ('ai-platform-foundation', 'gpu-compute'):
            continue  # prereqs only, no values

        lines += ['', f'# ── {block_name} ({btype}) ──']

        if btype == 'model-serving':
            lines += [
                f'{key}:',
                f'  model: {cfg.get("model", "")}',
                f'  image: {cfg.get("image", "")}',
            ]
            storage = cfg.get('storage', {})
            if storage.get('type') == 'oci':
                lines.append(f'  storageUri: {storage.get("uri", "")}')
            elif storage.get('type') == 's3':
                lines.append(f'  modelPath: {storage.get("path", "")}')
            res = cfg.get('resources', {})
            req = res.get('requests', {})
            lim = res.get('limits', {})
            lines += [
                '  resources:',
                '    requests:',
                f'      cpu: "{req.get("cpu", 1)}"',
                f'      memory: {req.get("memory", "4Gi")}',
                '    limits:',
                f'      cpu: "{lim.get("cpu", 4)}"',
                f'      memory: {lim.get("memory", "8Gi")}',
            ]

        elif btype == 'object-storage':
            lines += [
                f'{key}:',
                f'  image: quay.io/trustyai/modelmesh-minio-examples:latest',
                f'  storage: {cfg.get("storage", "20Gi")}',
            ]

        elif btype == 'guardrails-orchestrator':
            lines += [f'{key}:', '  # No user-configurable values']

    lines += [
        '',
        '# ── Custom components ─────────────────────────────────────────────',
    ]
    for comp_name, comp in spec.custom.items():
        key = _camel(comp_name)
        image = getattr(comp, 'image', '') or ''
        replicas = getattr(comp, 'replicas', 1)
        lines += [
            f'{key}:',
            f'  image: {image}',
            f'  replicas: {replicas}',
        ]

    return '\n'.join(lines) + '\n'


# ── NOTES.txt ────────────────────────────────────────────────────────────────


def build_notes(prereqs: list[str], app_name: str) -> str:
    lines = [
        f'{app_name} has been installed.',
        '',
        'PREREQUISITES (must be installed before this chart):',
    ]
    for p in prereqs:
        lines.append(f'  - {p}')
    lines += [
        '',
        'After install, retrieve the application route with:',
        f'  oc get route {app_name}-app -n {app_name} -o jsonpath="{{.spec.host}}"',
    ]
    return '\n'.join(lines) + '\n'


# ── Secrets script ───────────────────────────────────────────────────────────


def build_create_secrets_sh(app_name: str, secret_decls: list[dict]) -> str:
    """Generate scripts/create-secrets.sh for interactive secret creation."""
    lines = [
        '#!/usr/bin/env bash',
        '# Generated by quickpat compose -- do not edit',
        f'# Creates Kubernetes secrets for {app_name}.',
        '# Run before helm install if not using values.yaml secrets.',
        '',
        'set -euo pipefail',
        f'NAMESPACE="${{NAMESPACE:-{app_name}}}"',
        '',
        'echo "Creating secrets for namespace: $NAMESPACE"',
        '',
    ]

    for decl in secret_decls:
        name = decl['secret_name']
        keys = decl['keys']
        generate = decl.get('generate', False)

        lines.append(f'# Secret: {name}')
        key_args = []

        for k in keys:
            if generate:
                lines.append(
                    f'{k.upper().replace("-", "_")}=$(openssl rand -base64 16 | tr -dc a-zA-Z0-9 | head -c 20)'
                )
                key_args.append(f'  --from-literal={k}="${{{k.upper().replace("-", "_")}}}"')
            else:
                prompt_var = k.upper().replace('-', '_')
                lines.append(f'read -rsp "Enter {k} for {name}: " {prompt_var}; echo')
                key_args.append(f'  --from-literal={k}="${{{prompt_var}}}"')

        lines += [
            f'oc create secret generic {name} \\',
            *[f'{a} \\' for a in key_args[:-1]],
            f'{key_args[-1]}',
            f'  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -',
            '',
        ]

    lines += [
        'echo "Secrets created successfully."',
        'echo "You can now run: helm install {app_name} ./chart -n $NAMESPACE"'.format(app_name=app_name),
    ]
    return '\n'.join(lines) + '\n'
