"""Inline Kubernetes manifest generators for QS block types.

Each generator returns a dict of {filename: template_string} where the
template strings use Helm Go-template syntax ({{ .Values.xxx }}) so the
output chart supports helm install --set overrides.

Infrastructure blocks (ai-platform-foundation, gpu-compute) return only
prerequisite strings for NOTES.txt — they are not deployed by the QS chart.
"""


def _camel(name: str) -> str:
    """Convert kebab-case to camelCase for Helm values keys."""
    parts = name.split('-')
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


# ── Prerequisites (infrastructure blocks) ───────────────────────────────────


def ai_platform_foundation_prereqs(config: dict) -> list[str]:
    dsc = config.get('dsc', {})
    managed = [k for k, v in dsc.items() if v == 'Managed']
    channel = config.get('channel', 'fast')
    return [
        f'OpenShift AI operator installed (channel: {channel})',
        'OpenShift Serverless operator installed',
        'Red Hat OpenShift Service Mesh operator installed',
        'DataScienceCluster configured with: ' + (', '.join(managed) or 'kserve, dashboard'),
    ]


def gpu_compute_prereqs(config: dict) -> list[str]:
    channel = config.get('channel', 'v24.9')
    mig = config.get('mig_strategy', 'none')
    return [
        f'NVIDIA GPU Operator installed (channel: {channel})',
        'Node Feature Discovery operator installed',
        f'ClusterPolicy configured (mig_strategy: {mig})',
        'GPU node(s) available with nvidia.com/gpu resource',
    ]


# ── Model Serving ────────────────────────────────────────────────────────────


def model_serving_templates(block_name: str, config: dict) -> dict[str, str]:
    """Generate ServingRuntime + InferenceService for a model-serving block."""
    runtime = config.get('runtime', 'vllm')
    if runtime == 'vllm':
        sr = _vllm_serving_runtime(block_name, config)
    else:
        sr = _custom_serving_runtime(block_name, config)
    return {
        'servingruntime.yaml': sr,
        'inferenceservice.yaml': _inference_service(block_name, config),
    }


def _vllm_serving_runtime(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    vllm_args = config.get('vllm_args', {})
    extra_args = ''.join(
        # Boolean flags (empty string value) render as bare flags: --enable-auto-tool-choice
        # Value flags render as: --max-model-len=4096
        f'\n        - --{k.replace("_", "-")}' if v == '' else f'\n        - --{k.replace("_", "-")}={v}'
        for k, v in vllm_args.items()
    )
    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  supportedModelFormats:
    - name: vllm
      version: "1"
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: {{{{ .Values.{key}.image }}}}
      args:
        - --model=/mnt/models
        - --served-model-name={{{{ .Values.{key}.model }}}}{extra_args}
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
          nvidia.com/gpu: "1"
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
          nvidia.com/gpu: "1"
"""


def _custom_serving_runtime(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  supportedModelFormats:
    - name: {block_name}
      autoSelect: true
  multiModel: false
  containers:
    - name: kserve-container
      image: {{{{ .Values.{key}.image }}}}
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
"""


def _inference_service(block_name: str, config: dict) -> str:
    key = _camel(block_name)
    runtime = config.get('runtime', 'vllm')
    model_format = 'vllm' if runtime == 'vllm' else block_name
    gpu = config.get('gpu', False)
    replicas = config.get('replicas', {})
    min_r = replicas.get('min', 0) if isinstance(replicas, dict) else 0
    max_r = replicas.get('max', 1) if isinstance(replicas, dict) else 1
    storage = config.get('storage', {})
    storage_type = storage.get('type', 'oci')

    if storage_type == 'oci':
        storage_line = f'      storageUri: {{{{ .Values.{key}.storageUri }}}}'
    else:
        # S3 — references the MinIO data connection secret by name
        storage_line = (
            f'      storage:\n'
            f'        key: {storage.get("connection", "model-storage-data-connection")}\n'
            f'        path: {{{{ .Values.{key}.modelPath }}}}'
        )

    toleration = (
        '    tolerations:\n'
        '      - key: nvidia.com/gpu\n'
        '        operator: Exists\n'
        '        effect: NoSchedule\n'
    ) if gpu else ''

    return f"""\
# Generated by quickpat compose -- do not edit
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {block_name}
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  predictor:
    minReplicas: {min_r}
    maxReplicas: {max_r}
{toleration}    model:
      modelFormat:
        name: {model_format}
      runtime: {block_name}
{storage_line}
      resources:
        requests:
          cpu: {{{{ .Values.{key}.resources.requests.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.requests.memory }}}}
        limits:
          cpu: {{{{ .Values.{key}.resources.limits.cpu | quote }}}}
          memory: {{{{ .Values.{key}.resources.limits.memory }}}}
"""


# ── Object Storage (MinIO) ────────────────────────────────────────────────────


def object_storage_templates(
    block_name: str,
    config: dict,
    create_service_account: bool = True,
) -> dict[str, str]:
    """Generate provider-conditional Helm templates for an object-storage block.

    All templates use Helm `{{- if eq .Values.<key>.provider "..." }}` guards so
    the same chart handles minio, odf, and s3 — the operator selects the provider
    at install time via values.yaml or --set.

    Providers:
      minio — in-cluster MinIO with PVC, bucket-init container, credentials secret
      odf   — ObjectBucketClaim; setup Job reconciles OBC Secret → RHOAI format
      s3    — external S3; only data-connection Secret generated (no in-cluster pods)
    """
    key = _camel(block_name)
    init_models = config.get('init_models', [])
    models_csv = ','.join(init_models)
    bucket = config.get('bucket', 'data')
    sa_name = f'{block_name}-setup-sa'

    # ── MinIO: PVC ───────────────────────────────────────────────────────────
    pvc = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if eq .Values.{key}.provider "minio" }}}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {block_name}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{{{ .Values.{key}.storage }}}}
{{{{- end }}}}
"""

    # ── MinIO: Deployment + bucket-init container ────────────────────────────
    # The bucket-init initContainer runs after MinIO starts (readiness probe)
    # and creates the configured bucket if it does not already exist.
    # This replaces the separate configure-pipeline Job for bucket creation.
    models_init = ''
    if init_models:
        models_init = f"""\
        - name: download-models
          image: quay.io/rgeada/llm_downloader:latest
          env:
            - name: MODELS_PATH
              value: /mnt/models/huggingface
            - name: MODEL_IDS
              value: {models_csv!r}
          volumeMounts:
            - name: model-pvc
              mountPath: /mnt/models
"""

    deployment = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if eq .Values.{key}.provider "minio" }}}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {block_name}
  template:
    metadata:
      labels:
        app: {block_name}
    spec:
      initContainers:
{models_init}        - name: bucket-init
          image: quay.io/minio/mc:latest
          command: [sh, -c]
          args:
            - |
              until mc alias set local http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                echo "Waiting for MinIO..."; sleep 2
              done
              mc mb local/{{{{ .Values.{key}.bucket }}}} --ignore-existing
              echo "Bucket ready."
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_SECRET_ACCESS_KEY
      containers:
        - name: minio
          image: {{{{ .Values.{key}.image }}}}
          args:
            - server
            - /models
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {block_name}-credentials
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: model-pvc
              mountPath: /models
      volumes:
        - name: model-pvc
          persistentVolumeClaim:
            claimName: {block_name}-pvc
{{{{- end }}}}
"""

    # ── MinIO: Service ───────────────────────────────────────────────────────
    service = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if eq .Values.{key}.provider "minio" }}}}
apiVersion: v1
kind: Service
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  selector:
    app: {block_name}
  ports:
    - name: api
      port: 9000
      targetPort: 9000
{{{{- end }}}}
"""

    # ── ODF: ObjectBucketClaim ───────────────────────────────────────────────
    obc = f"""\
# Generated by quickpat compose -- do not edit
# ODF (OpenShift Data Foundation) creates a bucket and a paired Secret + ConfigMap
# named after this OBC. The obc-setup Job below reads those and writes the
# RHOAI-formatted data-connection Secret.
{{{{- if eq .Values.{key}.provider "odf" }}}}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {block_name}-obc
spec:
  generateBucketName: {bucket}
  storageClassName: {{{{ .Values.{key}.odfStorageClass | default "openshift-storage.noobaa.io" }}}}
{{{{- end }}}}
"""

    # ── ODF: optional RBAC + setup Job ──────────────────────────────────────
    rbac_block = ''
    if create_service_account:
        rbac_block = f"""\
{{{{- if eq .Values.{key}.provider "odf" }}}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {sa_name}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {block_name}-setup-role
rules:
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [get, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {block_name}-setup-rb
subjects:
  - kind: ServiceAccount
    name: {sa_name}
roleRef:
  kind: Role
  name: {block_name}-setup-role
  apiGroup: rbac.authorization.k8s.io
{{{{- end }}}}
"""
    else:
        rbac_block = f"""\
# RBAC not generated (--no-create-service-account).
# Pre-create before deploying:
#   oc create sa {sa_name} -n <namespace>
#   oc create role {block_name}-setup-role --verb=get,create,update,patch --resource=secrets,configmaps -n <namespace>
#   oc create rolebinding {block_name}-setup-rb --role={block_name}-setup-role --serviceaccount=<namespace>:{sa_name} -n <namespace>
"""

    obc_setup = f"""\
# Generated by quickpat compose -- do not edit
{rbac_block}
{{{{- if eq .Values.{key}.provider "odf" }}}}
# This Job reads the OBC-generated Secret and ConfigMap and writes a
# RHOAI-formatted data-connection Secret. It runs once after install
# and is removed on success by Helm's hook-delete-policy.
apiVersion: batch/v1
kind: Job
metadata:
  name: {block_name}-setup
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "5"
spec:
  template:
    spec:
      serviceAccountName: {sa_name}
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: quay.io/openshift/origin-cli:latest
          command: [sh, -c]
          args:
            - |
              set -e
              OBC_NAME={block_name}-obc
              # Wait for OBC to be bound
              until oc get secret $OBC_NAME 2>/dev/null; do
                echo "Waiting for OBC Secret..."; sleep 3
              done
              HOST=$(oc get configmap $OBC_NAME -o jsonpath='{{{{.data.BUCKET_HOST}}}}')
              PORT=$(oc get configmap $OBC_NAME -o jsonpath='{{{{.data.BUCKET_PORT}}}}')
              BUCKET=$(oc get configmap $OBC_NAME -o jsonpath='{{{{.data.BUCKET_NAME}}}}')
              ACCESS=$(oc get secret $OBC_NAME -o jsonpath='{{{{.data.AWS_ACCESS_KEY_ID}}}}' | base64 -d)
              SECRET=$(oc get secret $OBC_NAME -o jsonpath='{{{{.data.AWS_SECRET_ACCESS_KEY}}}}' | base64 -d)
              oc create secret generic {block_name}-data-connection \\
                --from-literal=AWS_S3_ENDPOINT="http://$HOST:$PORT" \\
                --from-literal=AWS_S3_BUCKET="$BUCKET" \\
                --from-literal=AWS_DEFAULT_REGION=us-east-1 \\
                --from-literal=AWS_ACCESS_KEY_ID="$ACCESS" \\
                --from-literal=AWS_SECRET_ACCESS_KEY="$SECRET" \\
                --dry-run=client -o yaml | oc apply -f -
              oc label secret {block_name}-data-connection \\
                opendatahub.io/dashboard=true opendatahub.io/managed=true \\
                --overwrite
              oc annotate secret {block_name}-data-connection \\
                opendatahub.io/connection-type=s3 --overwrite
              echo "Data connection created."
{{{{- end }}}}
"""

    # ── Credentials (minio + s3): explicit Secret from values ────────────────
    credentials = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if or (eq .Values.{key}.provider "minio") (eq .Values.{key}.provider "s3") }}}}
{{{{- if .Values.secrets.{key}AccessKey }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{{{ .Values.secrets.{key}AccessKey | quote }}}}
  AWS_SECRET_ACCESS_KEY: {{{{ .Values.secrets.{key}SecretKey | quote }}}}
{{{{- end }}}}
{{{{- end }}}}
"""

    # ── Data connection: always present, content varies by provider ──────────
    # This Secret is the interface contract — all consumers (ingestion pipeline,
    # LlamaStack, KServe model-serving blocks) reference it by name regardless
    # of which backend is behind it.
    data_connection = f"""\
# Generated by quickpat compose -- do not edit
# This Secret is the stable interface contract for the object-storage block.
# All consumers reference {block_name}-data-connection regardless of provider.
# For odf: populated by the {block_name}-setup Job above.
{{{{- if eq .Values.{key}.provider "minio" }}}}
{{{{- if .Values.secrets.{key}AccessKey }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-data-connection
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{{{ .Values.secrets.{key}AccessKey | quote }}}}
  AWS_SECRET_ACCESS_KEY: {{{{ .Values.secrets.{key}SecretKey | quote }}}}
  AWS_S3_ENDPOINT: http://{block_name}:9000
  AWS_S3_BUCKET: {{{{ .Values.{key}.bucket | quote }}}}
  AWS_DEFAULT_REGION: us-east-1
{{{{- end }}}}
{{{{- else if eq .Values.{key}.provider "s3" }}}}
{{{{- if .Values.secrets.{key}AccessKey }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-data-connection
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{{{ .Values.secrets.{key}AccessKey | quote }}}}
  AWS_SECRET_ACCESS_KEY: {{{{ .Values.secrets.{key}SecretKey | quote }}}}
  AWS_S3_ENDPOINT: {{{{ .Values.{key}.endpoint | default "https://s3.amazonaws.com" | quote }}}}
  AWS_S3_BUCKET: {{{{ .Values.{key}.bucket | quote }}}}
  AWS_DEFAULT_REGION: {{{{ .Values.{key}.region | default "us-east-1" | quote }}}}
{{{{- end }}}}
{{{{- end }}}}
# odf: data-connection Secret is written by the {block_name}-setup Job post-install.
"""

    return {
        'pvc.yaml': pvc,
        'deployment.yaml': deployment,
        'service.yaml': service,
        'obc.yaml': obc,
        'obc-setup.yaml': obc_setup,
        'credentials.yaml': credentials,
        'data-connection.yaml': data_connection,
    }


# ── Guardrails Orchestrator ───────────────────────────────────────────────────


def data_pipeline_templates(
    block_name: str,
    config: dict,
    resolved_inputs: dict = None,
) -> dict[str, str]:
    """Generate Tekton Pipeline + Task templates for a data-pipeline block.

    resolved_inputs contains the resolved block outputs for vector_store and
    object_storage input references, keyed by role:
        resolved_inputs['vector_store'] = {'block_name': 'db', 'config': {...}}
        resolved_inputs['object_storage'] = {'block_name': 'docs-storage', 'config': {...}}

    Generated resources:
        pipeline.yaml      — Tekton Pipeline wiring params to task
        ingest-task.yaml   — Tekton Task: fetch → chunk → embed → upsert
        pipeline-run.yaml  — Manual trigger template (apply to start a run)
        trigger.yaml       — CronJob trigger (when schedule != manual)
        rbac.yaml          — ServiceAccount + Role + RoleBinding for Tekton
    """
    resolved_inputs = resolved_inputs or {}
    key = _camel(block_name)
    sources = config.get('sources', [])
    schedule = config.get('schedule', 'manual')
    chunk_size = config.get('chunk_size', 512)

    # Resolve vector store connection details
    vs = resolved_inputs.get('vector_store', {})
    vs_name = vs.get('block_name', 'vector-store')
    vs_cfg = vs.get('config', {})
    vs_port = vs_cfg.get('port', 5432)
    vs_db = vs_cfg.get('database', 'vectordb')
    vs_endpoint = f'{vs_name}:{vs_port}'
    vs_secret = f'{vs_name}-secret'

    # Resolve object storage connection details
    os_block = resolved_inputs.get('object_storage', {})
    os_name = os_block.get('block_name', 'object-storage')
    os_cfg = os_block.get('config', {})
    os_bucket = os_cfg.get('bucket', 'data')
    os_endpoint = f'http://{os_name}:9000'
    os_creds_secret = f'{os_name}-credentials'
    os_dc_secret = f'{os_name}-data-connection'

    # Build source env vars for the task
    source_names = [s.get('name', f'source-{i}') for i, s in enumerate(sources)]

    sa_name = f'{block_name}-sa'

    # ── Tekton Pipeline ──────────────────────────────────────────────────────
    pipeline = f"""\
# Generated by quickpat compose -- do not edit
# Tekton Pipeline for document ingestion: fetch → chunk → embed → upsert
# Trigger manually: oc create -f pipeline-run.yaml
# Or let the CronJob trigger it on schedule.
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {block_name}-ingestion
  labels:
    app: {block_name}
spec:
  params:
    - name: vector-store-endpoint
      type: string
      default: {vs_endpoint}
      description: pgvector host:port
    - name: vector-store-db
      type: string
      default: {vs_db}
      description: pgvector database name
    - name: object-storage-endpoint
      type: string
      default: {os_endpoint}
      description: S3-compatible storage endpoint
    - name: object-storage-bucket
      type: string
      default: {os_bucket}
      description: Source document bucket
    - name: chunk-size
      type: string
      default: "{chunk_size}"
      description: Token chunk size for embedding
  tasks:
    - name: ingest
      taskRef:
        name: {block_name}-ingest
      params:
        - name: vector-store-endpoint
          value: $(params.vector-store-endpoint)
        - name: vector-store-db
          value: $(params.vector-store-db)
        - name: object-storage-endpoint
          value: $(params.object-storage-endpoint)
        - name: object-storage-bucket
          value: $(params.object-storage-bucket)
        - name: chunk-size
          value: $(params.chunk-size)
"""

    # ── Tekton Task ──────────────────────────────────────────────────────────
    ingest_task = f"""\
# Generated by quickpat compose -- do not edit
# Fetches documents from object storage, chunks them, generates embeddings,
# and upserts to pgvector. Override {{ .Values.{key}.image }} to use a
# different ingestion container.
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: {block_name}-ingest
  labels:
    app: {block_name}
spec:
  params:
    - name: vector-store-endpoint
      type: string
    - name: vector-store-db
      type: string
    - name: object-storage-endpoint
      type: string
    - name: object-storage-bucket
      type: string
    - name: chunk-size
      type: string
      default: "{chunk_size}"
  steps:
    - name: ingest
      image: {{{{ .Values.{key}.image }}}}
      env:
        # Vector store connection
        - name: PGVECTOR_HOST
          value: $(params.vector-store-endpoint)
        - name: PGVECTOR_DB
          value: $(params.vector-store-db)
        - name: PGVECTOR_USER
          value: vectordb
        - name: PGVECTOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {vs_secret}
              key: password
        # Object storage connection
        - name: AWS_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {os_dc_secret}
              key: AWS_S3_ENDPOINT
              optional: true
        - name: AWS_S3_BUCKET
          value: $(params.object-storage-bucket)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {os_creds_secret}
              key: AWS_ACCESS_KEY_ID
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {os_creds_secret}
              key: AWS_SECRET_ACCESS_KEY
              optional: true
        # Pipeline config
        - name: CHUNK_SIZE
          value: $(params.chunk-size)
        - name: OBJECT_STORAGE_ENDPOINT
          value: $(params.object-storage-endpoint)
"""

    # ── PipelineRun (manual trigger template) ────────────────────────────────
    pipeline_run = f"""\
# Generated by quickpat compose -- do not edit
# Apply this file to trigger a one-off ingestion run:
#   oc create -f pipeline-run.yaml -n <namespace>
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: {block_name}-ingestion-
  labels:
    app: {block_name}
spec:
  pipelineRef:
    name: {block_name}-ingestion
  taskRunTemplate:
    serviceAccountName: {sa_name}
  params:
    - name: vector-store-endpoint
      value: {vs_endpoint}
    - name: vector-store-db
      value: {vs_db}
    - name: object-storage-endpoint
      value: {os_endpoint}
    - name: object-storage-bucket
      value: {os_bucket}
    - name: chunk-size
      value: "{chunk_size}"
"""

    # ── CronJob trigger (scheduled runs) ────────────────────────────────────
    cron_schedule = {'hourly': '7 * * * *', 'daily': '7 2 * * *'}.get(schedule, '7 2 * * *')
    trigger = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if ne .Values.{key}.schedule "manual" }}}}
# CronJob that creates a PipelineRun on the configured schedule.
# Default schedules: hourly = "7 * * * *", daily = "7 2 * * *"
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {block_name}-trigger
  labels:
    app: {block_name}
spec:
  schedule: {{{{ .Values.{key}.cronSchedule | default "{cron_schedule}" | quote }}}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {sa_name}
          restartPolicy: OnFailure
          containers:
            - name: trigger
              image: quay.io/openshift/origin-cli:latest
              command: [sh, -c]
              args:
                - |
                  oc create -f - <<EOF
                  apiVersion: tekton.dev/v1
                  kind: PipelineRun
                  metadata:
                    generateName: {block_name}-scheduled-
                  spec:
                    pipelineRef:
                      name: {block_name}-ingestion
                    taskRunTemplate:
                      serviceAccountName: {sa_name}
                  EOF
{{{{- end }}}}
"""

    # ── RBAC: SA + Role + RoleBinding ────────────────────────────────────────
    rbac = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {sa_name}
  labels:
    app: {block_name}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {block_name}-role
rules:
  - apiGroups: [tekton.dev]
    resources: [pipelineruns]
    verbs: [create, get, list, watch]
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {block_name}-rb
subjects:
  - kind: ServiceAccount
    name: {sa_name}
roleRef:
  kind: Role
  name: {block_name}-role
  apiGroup: rbac.authorization.k8s.io
"""

    return {
        'pipeline.yaml': pipeline,
        'ingest-task.yaml': ingest_task,
        'pipeline-run.yaml': pipeline_run,
        'trigger.yaml': trigger,
        'rbac.yaml': rbac,
    }


def guardrails_orchestrator_templates(block_name: str, config: dict) -> dict[str, str]:
    detectors = config.get('detectors', {})
    detector_lines = '\n'.join(
        f'      {name}:\n        hostname: {det.get("endpoint", f"{name}-predictor")}\n        port: {det.get("port", 8000)}'
        for name, det in detectors.items()
    )

    chunker = config.get('chunker') or {}
    chunker_section = (
        f'    chunkers:\n'
        f'      sentence:\n'
        f'        hostname: {chunker.get("endpoint", "chunker-service")}\n'
        f'        port: {chunker.get("port", 8085)}\n'
    ) if chunker else ''

    lang_det = config.get('language_detector') or {}
    lang_section = (
        f'      language_detection:\n'
        f'        hostname: {lang_det.get("endpoint", "lingua-detector")}\n'
        f'        port: {lang_det.get("port", 8080)}\n'
    ) if lang_det else ''

    llm_endpoint = (config.get('llm') or {}).get('endpoint', 'llm-predictor')
    enable_built_in = str(config.get('enable_built_in_detectors', True)).lower()
    enable_gateway = str(config.get('enable_guardrails_gateway', False)).lower()
    otel_proto = config.get('otel_protocol', 'grpc')

    orchestrator = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: {block_name}
spec:
  enableBuiltInDetectors: {enable_built_in}
  enableGuardrailsGateway: {enable_gateway}
  orchestratorConfig: {block_name}-config
  otelExporter:
    otlpProtocol: {otel_proto}
  replicas: 1
"""

    configmap = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: ConfigMap
metadata:
  name: {block_name}-config
data:
  config.yaml: |
{chunker_section}    openai:
      service:
        hostname: {llm_endpoint}
    detectors:
{detector_lines}
{lang_section}"""

    return {
        'orchestrator.yaml': orchestrator,
        'configmap.yaml': configmap,
    }


# ── Values builder ───────────────────────────────────────────────────────────


def build_values(spec, secret_keys: list[str]) -> str:
    """Build values.yaml content from the ApplicationSpec.

    Returns a YAML string with documentation comments. Secrets are listed
    as empty-string placeholders — fill in before helm install or use
    scripts/create-secrets.sh.
    """
    lines = [
        '# Generated by quickpat compose -- do not edit',
        '# Override any value with: helm install <name> ./chart --set key=value',
        '',
        '# ── Secrets ──────────────────────────────────────────────────────────',
        '# Fill these in before helm install, or use scripts/create-secrets.sh',
        'secrets:',
    ]
    for key in secret_keys:
        lines.append(f'  {key}: ""')

    for block_name, block in spec.blocks.items():
        key = _camel(block_name)
        btype = block.block_type
        cfg = block.config or {}

        if btype in ('ai-platform-foundation', 'gpu-compute'):
            continue  # prereqs only, no values

        lines += ['', f'# ── {block_name} ({btype}) ──']

        if btype == 'model-serving':
            lines += [
                f'{key}:',
                f'  model: {cfg.get("model", "")}',
                f'  image: {cfg.get("image", "")}',
            ]
            storage = cfg.get('storage', {})
            if storage.get('type') == 'oci':
                lines.append(f'  storageUri: {storage.get("uri", "")}')
            elif storage.get('type') == 's3':
                lines.append(f'  modelPath: {storage.get("path", "")}')
            res = cfg.get('resources', {})
            req = res.get('requests', {})
            lim = res.get('limits', {})
            lines += [
                '  resources:',
                '    requests:',
                f'      cpu: "{req.get("cpu", 1)}"',
                f'      memory: {req.get("memory", "4Gi")}',
                '    limits:',
                f'      cpu: "{lim.get("cpu", 4)}"',
                f'      memory: {lim.get("memory", "8Gi")}',
            ]

        elif btype == 'object-storage':
            provider = cfg.get('provider', 'minio')
            lines += [
                f'{key}:',
                f'  # provider: which storage backend to use at deploy time.',
                f'  #   minio  = deploy MinIO in-cluster (default for bare metal)',
                f'  #   odf    = use OpenShift Data Foundation (requires ODF installed)',
                f'  #   s3     = use external AWS S3 or S3-compatible endpoint',
                f'  provider: {provider}',
                f'  bucket: {cfg.get("bucket", "data")}',
                f'  storage: {cfg.get("storage", "20Gi")}  # MinIO PVC size; ignored for odf and s3',
                f'  image: quay.io/trustyai/modelmesh-minio-examples:latest  # MinIO only',
                f'  endpoint: ""  # s3: e.g. https://s3.amazonaws.com; derived for minio and odf',
                f'  region: us-east-1  # s3 only',
                f'  odfStorageClass: openshift-storage.noobaa.io  # odf only',
            ]

        elif btype == 'data-pipeline':
            schedule = cfg.get('schedule', 'manual')
            cron = {'hourly': '7 * * * *', 'daily': '7 2 * * *'}.get(schedule, '7 2 * * *')
            lines += [
                f'{key}:',
                f'  # image: ingestion pipeline container',
                f'  image: quay.io/rh-ai-quickstart/ingestion-pipeline:latest',
                f'  # schedule: manual | hourly | daily',
                f'  schedule: {schedule}',
                f'  # cronSchedule: override the cron expression (ignored when schedule is manual)',
                f'  cronSchedule: "{cron}"',
            ]

        elif btype == 'guardrails-orchestrator':
            lines += [f'{key}:', '  # No user-configurable values']

    lines += [
        '',
        '# ── Custom components ─────────────────────────────────────────────',
    ]
    for comp_name, comp in spec.custom.items():
        key = _camel(comp_name)
        image = getattr(comp, 'image', '') or ''
        replicas = getattr(comp, 'replicas', 1)
        lines += [
            f'{key}:',
            f'  image: {image}',
            f'  replicas: {replicas}',
        ]

    return '\n'.join(lines) + '\n'


# ── NOTES.txt ────────────────────────────────────────────────────────────────


def build_notes(prereqs: list[str], app_name: str) -> str:
    lines = [
        f'{app_name} has been installed.',
        '',
        'PREREQUISITES (must be installed before this chart):',
    ]
    for p in prereqs:
        lines.append(f'  - {p}')
    lines += [
        '',
        'After install, retrieve the application route with:',
        f'  oc get route {app_name}-app -n {app_name} -o jsonpath="{{.spec.host}}"',
    ]
    return '\n'.join(lines) + '\n'


# ── Secrets script ───────────────────────────────────────────────────────────


def build_create_secrets_sh(
    app_name: str,
    secret_decls: list[dict],
    storage_providers: dict[str, str] = None,
) -> str:
    """Generate scripts/create-secrets.sh for interactive secret creation.

    storage_providers: {block_name: provider} for object-storage blocks.
    - minio: auto-generate credentials (random)
    - s3: prompt user for AWS credentials
    - odf: skip — OBC controller provides credentials automatically
    """
    storage_providers = storage_providers or {}
    lines = [
        '#!/usr/bin/env bash',
        '# Generated by quickpat compose -- do not edit',
        f'# Creates Kubernetes secrets for {app_name}.',
        '# Run before helm install if not using values.yaml secrets.',
        '',
        'set -euo pipefail',
        f'NAMESPACE="${{NAMESPACE:-{app_name}}}"',
        '',
        'echo "Creating secrets for namespace: $NAMESPACE"',
        '',
    ]

    # Storage provider credentials — handled separately with provider awareness
    for block_name, provider in storage_providers.items():
        key = _camel(block_name)
        if provider == 'odf':
            lines += [
                f'# {block_name} uses ODF — credentials are managed by the',
                f'# ObjectBucketClaim controller. No secrets to create here.',
                '',
            ]
        elif provider == 'minio':
            lines += [
                f'# {block_name} (MinIO) — auto-generating credentials',
                f'{key.upper()}_ACCESS=$(openssl rand -hex 16)',
                f'{key.upper()}_SECRET=$(openssl rand -hex 32)',
                f'oc create secret generic {block_name}-credentials \\',
                f'  --from-literal=AWS_ACCESS_KEY_ID="${{{key.upper()}_ACCESS}}" \\',
                f'  --from-literal=AWS_SECRET_ACCESS_KEY="${{{key.upper()}_SECRET}}" \\',
                f'  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -',
                '',
            ]
        elif provider == 's3':
            lines += [
                f'# {block_name} (S3) — enter your AWS credentials',
                f'read -rsp "Enter AWS_ACCESS_KEY_ID for {block_name}: " {key.upper()}_ACCESS; echo',
                f'read -rsp "Enter AWS_SECRET_ACCESS_KEY for {block_name}: " {key.upper()}_SECRET; echo',
                f'oc create secret generic {block_name}-credentials \\',
                f'  --from-literal=AWS_ACCESS_KEY_ID="${{{key.upper()}_ACCESS}}" \\',
                f'  --from-literal=AWS_SECRET_ACCESS_KEY="${{{key.upper()}_SECRET}}" \\',
                f'  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -',
                '',
            ]

    # All other declared secrets (API keys, etc.)
    for decl in secret_decls:
        name = decl['secret_name']
        keys = decl['keys']
        generate = decl.get('generate', False)

        lines.append(f'# Secret: {name}')
        key_args = []

        for k in keys:
            if generate:
                lines.append(
                    f'{k.upper().replace("-", "_")}=$(openssl rand -base64 16 | tr -dc a-zA-Z0-9 | head -c 20)'
                )
                key_args.append(f'  --from-literal={k}="${{{k.upper().replace("-", "_")}}}"')
            else:
                prompt_var = k.upper().replace('-', '_')
                lines.append(f'read -rsp "Enter {k} for {name}: " {prompt_var}; echo')
                key_args.append(f'  --from-literal={k}="${{{prompt_var}}}"')

        if key_args:
            lines += [
                f'oc create secret generic {name} \\',
                *[f'{a} \\' for a in key_args[:-1]],
                f'{key_args[-1]}',
                f'  -n "$NAMESPACE" --dry-run=client -o yaml | oc apply -f -',
                '',
            ]

    lines += [
        'echo "Secrets created successfully."',
        'echo "You can now run: helm install {app_name} ./chart -n $NAMESPACE"'.format(app_name=app_name),
    ]
    return '\n'.join(lines) + '\n'
