"""QS (Quickstart) chart generator.

Writes a self-contained Helm chart to qs-out/ inside the application repo.
Handles:
  - Inline Kubernetes manifests for application-layer blocks
  - Custom component charts copied from the application repo
  - values.yaml with config defaults + secrets placeholders
  - scripts/create-secrets.sh for interactive secret creation
  - NOTES.txt listing cluster prerequisites (operators, DSC)
  - README.md with install instructions
"""

import json
import re
import shutil
from pathlib import Path

from .block_templates import (
    ai_platform_foundation_prereqs,
    gpu_compute_prereqs,
    model_serving_templates,
    object_storage_templates,
    data_pipeline_templates,
    llama_stack_templates,
    guardrails_orchestrator_templates,
    build_values,
    build_notes,
    build_create_secrets_sh,
    _camel,
)


def _secret_value_key(secret_name: str, field_name: str) -> str:
    """camelCase values.yaml key for a top-level secret field.

    Normalises both kebab- and snake_case (e.g. gemini + api_key -> geminiApiKey)
    so the generated Secret template and values.yaml always reference the same
    key. This is the Helm values key only; the Kubernetes Secret data key keeps
    the raw field name (api_key).
    """
    parts = [p for p in re.split(r'[-_/]', f'{secret_name}-{field_name}') if p]
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


class QSGenerator:
    def __init__(self, spec, config: dict, output_dir: Path):
        self.spec = spec
        self.config = config
        self.output_dir = output_dir
        self.chart_dir = output_dir / 'chart'
        self.templates_dir = self.chart_dir / 'templates'
        self.scripts_dir = output_dir / 'scripts'

    def generate(self):
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.chart_dir.mkdir(exist_ok=True)
        self.templates_dir.mkdir(exist_ok=True)
        self.scripts_dir.mkdir(exist_ok=True)

        prereqs = self._collect_prereqs()
        secret_decls = self._collect_secret_decls()
        secret_keys = self._collect_secret_keys(secret_decls)

        self._write_chart_yaml()
        self._write_values_yaml(secret_keys)
        self._write_notes_txt(prereqs)
        self._write_block_templates()
        self._write_top_level_secret_templates()
        self._write_custom_components()
        self._merge_custom_chart_values()
        self._write_create_secrets_sh(secret_decls)
        self._write_readme(prereqs)
        self._write_spec_docs()

    # ── Chart.yaml ───────────────────────────────────────────────────────────

    def _write_chart_yaml(self):
        content = (
            '# Generated by quickpat compose -- do not edit\n'
            f'apiVersion: v2\n'
            f'name: {self.spec.name}\n'
            f'description: {self.spec.description or self.spec.name}\n'
            f'version: 0.1.0\n'
            f'type: application\n'
        )
        (self.chart_dir / 'Chart.yaml').write_text(content)

    # ── values.yaml ──────────────────────────────────────────────────────────

    def _write_values_yaml(self, secret_keys: list[str]):
        content = build_values(self.spec, secret_keys)
        (self.chart_dir / 'values.yaml').write_text(content)

    # ── NOTES.txt ────────────────────────────────────────────────────────────

    def _write_notes_txt(self, prereqs: list[str]):
        content = build_notes(prereqs, self.spec.name)
        (self.templates_dir / 'NOTES.txt').write_text(content)

    # ── Block templates ───────────────────────────────────────────────────────

    def _write_block_templates(self):
        for block_name, block in self.spec.blocks.items():
            btype = block.block_type
            cfg = block.config or {}

            if btype in ('ai-platform-foundation', 'gpu-compute'):
                continue  # prereqs only

            block_dir = self.templates_dir / block_name
            block_dir.mkdir(exist_ok=True)

            if btype == 'model-serving':
                templates = model_serving_templates(block_name, cfg)
            elif btype == 'object-storage':
                templates = object_storage_templates(
                    block_name, cfg,
                    create_service_account=self.config.get('create_service_account', True),
                )
            elif btype == 'guardrails-orchestrator':
                templates = guardrails_orchestrator_templates(block_name, cfg)
            elif btype == 'vector-store':
                templates = self._vector_store_templates(block_name, cfg)
            elif btype == 'llama-stack':
                templates = llama_stack_templates(
                    block_name, cfg,
                    resolved_inputs=self._resolve_inputs(block),
                )
            elif btype == 'data-pipeline':
                templates = data_pipeline_templates(
                    block_name, cfg,
                    resolved_inputs=self._resolve_inputs(block),
                )
            else:
                templates = {}

            for filename, content in templates.items():
                (block_dir / filename).write_text(content)

    def _resolve_inputs(self, block) -> dict:
        """Resolve a block's inputs: dict to concrete block configs.

        Returns {role: {'block_name': str, 'block_type': str, 'config': dict}}
        for each declared input reference. Silently skips references that don't
        match a known block name.
        """
        resolved = {}
        for role, ref_name in (block.inputs or {}).items():
            ref_block = self.spec.blocks.get(ref_name)
            if ref_block:
                resolved[role] = {
                    'block_name': ref_name,
                    'block_type': ref_block.block_type,
                    'config': ref_block.config or {},
                }
        return resolved

    def _vector_store_templates(self, block_name: str, config: dict) -> dict[str, str]:
        key = _camel(block_name)
        database = config.get('database', 'vectordb')
        port = config.get('port', 5432)

        service = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: Service
metadata:
  name: {block_name}
spec:
  selector:
    app: {block_name}
  ports:
    - port: {port}
      targetPort: {port}
"""
        deployment = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {block_name}
  template:
    metadata:
      labels:
        app: {block_name}
    spec:
      containers:
        - name: pgvector
          image: pgvector/pgvector:pg16
          env:
            - name: POSTGRESQL_DATABASE
              value: {database}
            - name: POSTGRESQL_USER
              value: vectordb
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {block_name}-secret
                  key: password
          ports:
            - containerPort: {port}
"""
        secret = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if .Values.secrets.{key}Password }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-secret
type: Opaque
stringData:
  password: {{{{ .Values.secrets.{key}Password | quote }}}}
{{{{- end }}}}
"""
        return {
            'deployment.yaml': deployment,
            'service.yaml': service,
            'secret.yaml': secret,
        }

    # ── Top-level secrets (plain Secrets, no Vault) ────────────────────────────

    def _write_top_level_secret_templates(self):
        """Emit a plain kind: Secret per top-level secret.

        The VP path renders these as ExternalSecrets pulling from Vault. The QS
        path has no Vault/ESO, so it materialises the same target Secrets
        directly from .Values.secrets.* (populated via --set or
        scripts/create-secrets.sh). Each Secret is gated so it is only created
        when at least one of its fields is provided — optional providers
        (onMissingValue: skip) simply stay absent.
        """
        if not self.spec.top_level_secrets:
            return
        secrets_dir = self.templates_dir / 'secrets'
        secrets_dir.mkdir(exist_ok=True)
        for sec in self.spec.top_level_secrets:
            field_names = [f.name for f in sec.fields] or [sec.name]
            value_keys = {fn: _secret_value_key(sec.name, fn) for fn in field_names}
            field_defaults = {f.name: f.value for f in sec.fields if f.value is not None}
            guard = ' '.join(f'.Values.secrets.{value_keys[fn]}' for fn in field_names)
            lines = [
                '# Generated by quickpat compose -- do not edit',
                f'{{{{- if or {guard} }}}}',
                'apiVersion: v1',
                'kind: Secret',
                'metadata:',
                f'  name: {sec.name}',
                'type: Opaque',
                'stringData:',
            ]
            for fn in field_names:
                vk = value_keys[fn]
                default = field_defaults.get(fn)
                if default is not None:
                    default_lit = json.dumps(str(default))
                    lines.append(
                        f'  {fn}: {{{{ .Values.secrets.{vk} | default {default_lit} | quote }}}}'
                    )
                else:
                    lines += [
                        f'{{{{- if .Values.secrets.{vk} }}}}',
                        f'  {fn}: {{{{ .Values.secrets.{vk} | quote }}}}',
                        '{{- end }}',
                    ]
            lines.append('{{- end }}')
            fname = f'{sec.name}.yaml'.replace('/', '-')
            (secrets_dir / fname).write_text('\n'.join(lines) + '\n')

    # ── Custom components ─────────────────────────────────────────────────────

    def _write_custom_components(self):
        existing = self.config.get('existing_custom_charts', set())
        spec_dir = self.config.get('spec_dir')

        for comp_name, comp in self.spec.custom.items():
            # deploy: manual components are build-time only — not in the QS chart
            if getattr(comp, 'deploy', 'argocd') == 'manual':
                continue

            dst = self.templates_dir / comp_name
            if comp_name in existing and spec_dir:
                # Copy real chart templates directly into chart/templates/<comp>/
                src_templates = Path(spec_dir) / 'charts' / comp_name / 'templates'
                if dst.exists():
                    shutil.rmtree(dst)
                if src_templates.exists():
                    self._copy_templates_no_externalsecrets(src_templates, dst)
                else:
                    dst.mkdir(exist_ok=True)
            else:
                # Stub: create an empty NOTES.txt so helm lint accepts the directory
                dst.mkdir(exist_ok=True)
                (dst / 'NOTES.txt').write_text(
                    f'# {comp_name} — chart not yet implemented\n'
                )

    @classmethod
    def _is_external_secret(cls, path: Path) -> bool:
        """True if a template file declares only ExternalSecret resource(s).

        A Quickstart has no External Secrets Operator, so ExternalSecrets from
        hand-written charts are dropped and replaced by the plain Secrets in
        templates/secrets/ (see _write_top_level_secret_templates).
        """
        if path.suffix not in ('.yaml', '.yml'):
            return False
        try:
            text = path.read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            return False
        # A file "is" an ExternalSecret only if every meaningful document in it
        # is one — so stripping the ExternalSecret docs leaves nothing behind.
        return (cls._has_meaningful_yaml(text)
                and not cls._has_meaningful_yaml(cls._strip_external_secret_docs(text)))

    @staticmethod
    def _doc_is_external_secret(doc: str) -> bool:
        """True if a single YAML document's first kind: is ExternalSecret."""
        for line in doc.splitlines():
            stripped = line.strip()
            if stripped.startswith('kind:'):
                return stripped.split(':', 1)[1].strip().strip('"\'') == 'ExternalSecret'
        return False

    @classmethod
    def _strip_external_secret_docs(cls, text: str) -> str:
        """Return text with any ExternalSecret YAML documents removed.

        Handles multi-document files: a file mixing a plain Secret with an
        ExternalSecret keeps the Secret and drops only the ExternalSecret doc.
        """
        docs = re.split(r'(?m)^---[ \t]*$\n?', text)
        kept = [d.strip('\n') for d in docs
                if d.strip() and not cls._doc_is_external_secret(d)]
        return '\n---\n'.join(kept)

    @staticmethod
    def _has_meaningful_yaml(text: str) -> bool:
        """True if text has any non-blank, non-comment, non-separator line."""
        for line in text.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith('#') and stripped != '---':
                return True
        return False

    def _copy_templates_no_externalsecrets(self, src: Path, dst: Path):
        """Copy a chart's templates/ into the QS chart, dropping ExternalSecrets.

        ExternalSecret documents are removed at the document level, so a file
        that mixes a plain Secret with an ExternalSecret keeps the Secret.
        """
        dst.mkdir(parents=True, exist_ok=True)
        for item in src.rglob('*'):
            rel = item.relative_to(src)
            target = dst / rel
            if item.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                continue
            if item.suffix not in ('.yaml', '.yml'):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)
                continue
            try:
                text = item.read_text(encoding='utf-8')
            except (OSError, UnicodeDecodeError):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)
                continue
            stripped = self._strip_external_secret_docs(text)
            if not self._has_meaningful_yaml(stripped):
                continue  # file was purely ExternalSecret(s) — drop it
            target.parent.mkdir(parents=True, exist_ok=True)
            if stripped == text:
                shutil.copy2(item, target)
            else:
                if not stripped.endswith('\n'):
                    stripped += '\n'
                target.write_text(stripped, encoding='utf-8')

    # Vault/ESO-only keys from hand-written charts — meaningless in the QS path
    # once ExternalSecrets are stripped, so they are not merged into values.yaml.
    _ESO_ONLY_VALUE_KEYS = frozenset({'secretStoreRef', 'vaultPrefix', 'refreshInterval'})

    def _merge_custom_chart_values(self):
        """Merge values.yaml from each copied custom chart into the QS chart values.

        When templates from a chart (e.g. pattern-secrets) reference
        .Values.secretStoreRef or .Values.vaultPrefix, those defaults must
        exist in the QS chart's top-level values.yaml or helm lint/template
        will fail with nil-pointer errors.

        Only keys not already present in the generated values.yaml are added,
        so explicitly configured values always take precedence.
        """
        import yaml as _yaml

        spec_dir = self.config.get('spec_dir')
        existing = self.config.get('existing_custom_charts', set())
        if not spec_dir:
            return

        values_path = self.chart_dir / 'values.yaml'
        current_text = values_path.read_text(encoding='utf-8')
        current = _yaml.safe_load(current_text) or {}

        to_merge = {}
        for comp_name, comp in self.spec.custom.items():
            # Skip manual components — their templates weren't written into the QS chart
            if getattr(comp, 'deploy', 'argocd') == 'manual':
                continue
            if comp_name not in existing:
                continue
            chart_values_path = Path(spec_dir) / 'charts' / comp_name / 'values.yaml'
            if not chart_values_path.exists():
                continue
            chart_values = _yaml.safe_load(chart_values_path.read_text(encoding='utf-8')) or {}
            for key, val in chart_values.items():
                if key in self._ESO_ONLY_VALUE_KEYS:
                    continue  # Vault/ESO config — not used in the QS path
                # Add only keys absent from both the current values and already-merged ones.
                # When two charts both define the same key, the first one wins — warn so
                # the author knows to resolve the conflict explicitly.
                if key not in current and key not in to_merge:
                    to_merge[key] = val
                elif key in to_merge and to_merge[key] != val:
                    import warnings as _w
                    _w.warn(
                        f"QS values conflict: '{key}' defined in multiple custom charts. "
                        f"Using first value; override in chart/{key} if needed.",
                        stacklevel=2,
                    )

        if not to_merge:
            return

        with open(values_path, 'a', encoding='utf-8') as f:
            f.write('\n# ── Values from included charts ──────────────────────────────────────\n')
            f.write(_yaml.dump(to_merge, default_flow_style=False, sort_keys=False))

    # ── Secrets ───────────────────────────────────────────────────────────────

    def _collect_secret_decls(self) -> list[dict]:
        decls = []
        for block_name, block in self.spec.blocks.items():
            for sec_name, sec_decl in block.secrets.items():
                decls.append({
                    'secret_name': f'{block_name}-{sec_name}'.replace('/', '-'),
                    'keys': [sec_decl.key or sec_name],
                    'generate': sec_decl.generate,
                    'optional': False,
                })
        # Top-level secrets: (spec.secrets:) — provider API keys, SSH keys, etc.
        # In the VP path these become ExternalSecrets pulling from Vault. In the
        # QS path there is no Vault, so we create the target Kubernetes Secrets
        # directly (values.yaml / create-secrets.sh). The Secret name matches the
        # ExternalSecret target.name (== the top-level secret name) so consuming
        # charts resolve it identically under both paths.
        for sec in self.spec.top_level_secrets:
            field_names = [f.name for f in sec.fields] or [sec.name]
            field_defaults = {
                f.name: {'value': f.value, 'path': f.path}
                for f in sec.fields
                if f.value is not None or f.path is not None
            }
            decls.append({
                'secret_name': sec.name.replace('/', '-'),
                'keys': field_names,
                'generate': sec.on_missing == 'generate',
                'optional': sec.on_missing == 'skip',
                'field_defaults': field_defaults,
            })
        return decls

    def _collect_secret_keys(self, decls: list[dict]) -> list[str]:
        """Derive values.yaml secrets section keys from spec declarations.

        Key naming: secrets.<blockKey>AccessKey / secrets.<blockKey>SecretKey
        for object-storage blocks that use minio or s3. odf blocks skip secrets
        entirely (OBC controller handles credentials). Block-level secret
        declarations (e.g. vLLM API key) use camelCase of block+key name.
        """
        keys = []
        for block_name, block in self.spec.blocks.items():
            bkey = _camel(block_name)
            if block.block_type == 'object-storage':
                provider = (block.config or {}).get('provider', 'minio')
                if provider in ('minio', 's3'):
                    keys += [f'{bkey}AccessKey', f'{bkey}SecretKey']
                # odf: no credentials in values — OBC controller provides them
                continue
            for sec_name, sec_decl in block.secrets.items():
                raw_key = sec_decl.key or sec_name
                keys.append(_camel(f'{block_name}-{raw_key}'.replace('/', '-')))
        # Top-level secrets contribute one values key per field (camelCase of
        # <secret-name>-<field>), so `helm install --set secrets.<key>=...` and
        # the generated Secret templates line up.
        for sec in self.spec.top_level_secrets:
            field_names = [f.name for f in sec.fields] or [sec.name]
            for fn in field_names:
                keys.append(_secret_value_key(sec.name, fn))
        return keys

    def _collect_storage_providers(self) -> dict[str, str]:
        """Return {block_name: provider} for all object-storage blocks."""
        return {
            name: (block.config or {}).get('provider', 'minio')
            for name, block in self.spec.blocks.items()
            if block.block_type == 'object-storage'
        }

    # ── Create-secrets script ─────────────────────────────────────────────────

    def _write_create_secrets_sh(self, secret_decls: list[dict]):
        providers = self._collect_storage_providers()
        content = build_create_secrets_sh(self.spec.name, secret_decls, providers)
        path = self.scripts_dir / 'create-secrets.sh'
        path.write_text(content)
        path.chmod(0o755)

    # ── README ────────────────────────────────────────────────────────────────

    def _write_readme(self, prereqs: list[str]):
        name = self.spec.name
        lines = [
            f'# {name}',
            '',
            self.spec.description or '',
            '',
            '## Prerequisites',
            '',
            'Install these on your cluster before deploying:',
            '',
        ]
        for p in prereqs:
            lines.append(f'- {p}')
        lines += [
            '',
            '## Install',
            '',
            '**Option A — values.yaml secrets** (CI / automated):',
            '',
            '```bash',
            f'helm install {name} ./chart \\',
            '  --set secrets.vllmApiKey=<your-key> \\',
            '  --set secrets.minioAccessKey=admin \\',
            '  --set secrets.minioSecretKey=adminpassword \\',
            f'  -n {name} --create-namespace',
            '```',
            '',
            '**Option B — create secrets out-of-band** (interactive / production):',
            '',
            '```bash',
            f'oc new-project {name}',
            './scripts/create-secrets.sh',
            f'helm install {name} ./chart -n {name}',
            '```',
            '',
            '## Regenerate',
            '',
            'This chart is generated from `spec.yaml` by quickpat:',
            '',
            '```bash',
            'quickpat compose spec.yaml --format qs',
            '```',
        ]
        (self.output_dir / 'README.md').write_text('\n'.join(lines) + '\n')

    # ── Prereqs collector ─────────────────────────────────────────────────────

    def _collect_prereqs(self) -> list[str]:
        prereqs = []
        for block_name, block in self.spec.blocks.items():
            cfg = block.config or {}
            if block.block_type == 'ai-platform-foundation':
                prereqs.extend(ai_platform_foundation_prereqs(cfg))
            elif block.block_type == 'gpu-compute':
                prereqs.extend(gpu_compute_prereqs(cfg))
        return prereqs

    def _write_spec_docs(self):
        """Process and write spec docs: entries into the QS output directory.

        Runs after _write_readme() so spec-authored docs overwrite the
        auto-generated README when target: README.md is declared.
        """
        from .doc_filter import process_docs
        process_docs(
            doc_entries=self.config.get('docs', []),
            spec_dir=self.config.get('spec_dir'),
            output_dir=self.output_dir,
            deploy_mode='qs',
        )
