"""QS (Quickstart) chart generator.

Writes a self-contained Helm chart to qs-out/ inside the application repo.
Handles:
  - Inline Kubernetes manifests for application-layer blocks
  - Custom component charts copied from the application repo
  - values.yaml with config defaults + secrets placeholders
  - scripts/create-secrets.sh for interactive secret creation
  - NOTES.txt listing cluster prerequisites (operators, DSC)
  - README.md with install instructions
"""

import shutil
from pathlib import Path

from .block_templates import (
    ai_platform_foundation_prereqs,
    gpu_compute_prereqs,
    model_serving_templates,
    object_storage_templates,
    data_pipeline_templates,
    llama_stack_templates,
    guardrails_orchestrator_templates,
    build_values,
    build_notes,
    build_create_secrets_sh,
    _camel,
)


class QSGenerator:
    def __init__(self, spec, config: dict, output_dir: Path):
        self.spec = spec
        self.config = config
        self.output_dir = output_dir
        self.chart_dir = output_dir / 'chart'
        self.templates_dir = self.chart_dir / 'templates'
        self.scripts_dir = output_dir / 'scripts'

    def generate(self):
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.chart_dir.mkdir(exist_ok=True)
        self.templates_dir.mkdir(exist_ok=True)
        self.scripts_dir.mkdir(exist_ok=True)

        prereqs = self._collect_prereqs()
        secret_decls = self._collect_secret_decls()
        secret_keys = self._collect_secret_keys(secret_decls)

        self._write_chart_yaml()
        self._write_values_yaml(secret_keys)
        self._write_notes_txt(prereqs)
        self._write_block_templates()
        self._write_custom_components()
        self._write_create_secrets_sh(secret_decls)
        self._write_readme(prereqs)

    # ── Chart.yaml ───────────────────────────────────────────────────────────

    def _write_chart_yaml(self):
        content = (
            '# Generated by quickpat compose -- do not edit\n'
            f'apiVersion: v2\n'
            f'name: {self.spec.name}\n'
            f'description: {self.spec.description or self.spec.name}\n'
            f'version: 0.1.0\n'
            f'type: application\n'
        )
        (self.chart_dir / 'Chart.yaml').write_text(content)

    # ── values.yaml ──────────────────────────────────────────────────────────

    def _write_values_yaml(self, secret_keys: list[str]):
        content = build_values(self.spec, secret_keys)
        (self.chart_dir / 'values.yaml').write_text(content)

    # ── NOTES.txt ────────────────────────────────────────────────────────────

    def _write_notes_txt(self, prereqs: list[str]):
        content = build_notes(prereqs, self.spec.name)
        (self.templates_dir / 'NOTES.txt').write_text(content)

    # ── Block templates ───────────────────────────────────────────────────────

    def _write_block_templates(self):
        for block_name, block in self.spec.blocks.items():
            btype = block.block_type
            cfg = block.config or {}

            if btype in ('ai-platform-foundation', 'gpu-compute'):
                continue  # prereqs only

            block_dir = self.templates_dir / block_name
            block_dir.mkdir(exist_ok=True)

            if btype == 'model-serving':
                templates = model_serving_templates(block_name, cfg)
            elif btype == 'object-storage':
                templates = object_storage_templates(
                    block_name, cfg,
                    create_service_account=self.config.get('create_service_account', True),
                )
            elif btype == 'guardrails-orchestrator':
                templates = guardrails_orchestrator_templates(block_name, cfg)
            elif btype == 'vector-store':
                templates = self._vector_store_templates(block_name, cfg)
            elif btype == 'llama-stack':
                templates = llama_stack_templates(
                    block_name, cfg,
                    resolved_inputs=self._resolve_inputs(block),
                )
            elif btype == 'data-pipeline':
                templates = data_pipeline_templates(
                    block_name, cfg,
                    resolved_inputs=self._resolve_inputs(block),
                )
            else:
                templates = {}

            for filename, content in templates.items():
                (block_dir / filename).write_text(content)

    def _resolve_inputs(self, block) -> dict:
        """Resolve a block's inputs: dict to concrete block configs.

        Returns {role: {'block_name': str, 'block_type': str, 'config': dict}}
        for each declared input reference. Silently skips references that don't
        match a known block name.
        """
        resolved = {}
        for role, ref_name in (block.inputs or {}).items():
            ref_block = self.spec.blocks.get(ref_name)
            if ref_block:
                resolved[role] = {
                    'block_name': ref_name,
                    'block_type': ref_block.block_type,
                    'config': ref_block.config or {},
                }
        return resolved

    def _vector_store_templates(self, block_name: str, config: dict) -> dict[str, str]:
        key = _camel(block_name)
        database = config.get('database', 'vectordb')
        port = config.get('port', 5432)

        service = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: v1
kind: Service
metadata:
  name: {block_name}
spec:
  selector:
    app: {block_name}
  ports:
    - port: {port}
      targetPort: {port}
"""
        deployment = f"""\
# Generated by quickpat compose -- do not edit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {block_name}
  labels:
    app: {block_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {block_name}
  template:
    metadata:
      labels:
        app: {block_name}
    spec:
      containers:
        - name: pgvector
          image: pgvector/pgvector:pg16
          env:
            - name: POSTGRESQL_DATABASE
              value: {database}
            - name: POSTGRESQL_USER
              value: vectordb
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {block_name}-secret
                  key: password
          ports:
            - containerPort: {port}
"""
        secret = f"""\
# Generated by quickpat compose -- do not edit
{{{{- if .Values.secrets.{key}Password }}}}
apiVersion: v1
kind: Secret
metadata:
  name: {block_name}-secret
type: Opaque
stringData:
  password: {{{{ .Values.secrets.{key}Password | quote }}}}
{{{{- end }}}}
"""
        return {
            'deployment.yaml': deployment,
            'service.yaml': service,
            'secret.yaml': secret,
        }

    # ── Custom components ─────────────────────────────────────────────────────

    def _write_custom_components(self):
        existing = self.config.get('existing_custom_charts', set())
        spec_dir = self.config.get('spec_dir')

        for comp_name in self.spec.custom:
            dst = self.templates_dir / comp_name
            if comp_name in existing and spec_dir:
                # Copy real chart templates directly into chart/templates/<comp>/
                src_templates = Path(spec_dir) / 'charts' / comp_name / 'templates'
                if dst.exists():
                    shutil.rmtree(dst)
                if src_templates.exists():
                    shutil.copytree(src_templates, dst)
                else:
                    dst.mkdir(exist_ok=True)
            else:
                dst.mkdir(exist_ok=True)
                (dst / '.gitkeep').touch()

    # ── Secrets ───────────────────────────────────────────────────────────────

    def _collect_secret_decls(self) -> list[dict]:
        decls = []
        for block_name, block in self.spec.blocks.items():
            for sec_name, sec_decl in block.secrets.items():
                decls.append({
                    'secret_name': f'{block_name}-{sec_name}'.replace('/', '-'),
                    'keys': [sec_decl.key or sec_name],
                    'generate': sec_decl.generate,
                })
        return decls

    def _collect_secret_keys(self, decls: list[dict]) -> list[str]:
        """Derive values.yaml secrets section keys from spec declarations.

        Key naming: secrets.<blockKey>AccessKey / secrets.<blockKey>SecretKey
        for object-storage blocks that use minio or s3. odf blocks skip secrets
        entirely (OBC controller handles credentials). Block-level secret
        declarations (e.g. vLLM API key) use camelCase of block+key name.
        """
        keys = []
        for block_name, block in self.spec.blocks.items():
            bkey = _camel(block_name)
            if block.block_type == 'object-storage':
                provider = (block.config or {}).get('provider', 'minio')
                if provider in ('minio', 's3'):
                    keys += [f'{bkey}AccessKey', f'{bkey}SecretKey']
                # odf: no credentials in values — OBC controller provides them
                continue
            for sec_name, sec_decl in block.secrets.items():
                raw_key = sec_decl.key or sec_name
                keys.append(_camel(f'{block_name}-{raw_key}'.replace('/', '-')))
        return keys

    def _collect_storage_providers(self) -> dict[str, str]:
        """Return {block_name: provider} for all object-storage blocks."""
        return {
            name: (block.config or {}).get('provider', 'minio')
            for name, block in self.spec.blocks.items()
            if block.block_type == 'object-storage'
        }

    # ── Create-secrets script ─────────────────────────────────────────────────

    def _write_create_secrets_sh(self, secret_decls: list[dict]):
        providers = self._collect_storage_providers()
        content = build_create_secrets_sh(self.spec.name, secret_decls, providers)
        path = self.scripts_dir / 'create-secrets.sh'
        path.write_text(content)
        path.chmod(0o755)

    # ── README ────────────────────────────────────────────────────────────────

    def _write_readme(self, prereqs: list[str]):
        name = self.spec.name
        lines = [
            f'# {name}',
            '',
            self.spec.description or '',
            '',
            '## Prerequisites',
            '',
            'Install these on your cluster before deploying:',
            '',
        ]
        for p in prereqs:
            lines.append(f'- {p}')
        lines += [
            '',
            '## Install',
            '',
            '**Option A — values.yaml secrets** (CI / automated):',
            '',
            '```bash',
            f'helm install {name} ./chart \\',
            '  --set secrets.vllmApiKey=<your-key> \\',
            '  --set secrets.minioAccessKey=admin \\',
            '  --set secrets.minioSecretKey=adminpassword \\',
            f'  -n {name} --create-namespace',
            '```',
            '',
            '**Option B — create secrets out-of-band** (interactive / production):',
            '',
            '```bash',
            f'oc new-project {name}',
            './scripts/create-secrets.sh',
            f'helm install {name} ./chart -n {name}',
            '```',
            '',
            '## Regenerate',
            '',
            'This chart is generated from `spec.yaml` by quickpat:',
            '',
            '```bash',
            'quickpat compose spec.yaml --format qs',
            '```',
        ]
        (self.output_dir / 'README.md').write_text('\n'.join(lines) + '\n')

    # ── Prereqs collector ─────────────────────────────────────────────────────

    def _collect_prereqs(self) -> list[str]:
        prereqs = []
        for block_name, block in self.spec.blocks.items():
            cfg = block.config or {}
            if block.block_type == 'ai-platform-foundation':
                prereqs.extend(ai_platform_foundation_prereqs(cfg))
            elif block.block_type == 'gpu-compute':
                prereqs.extend(gpu_compute_prereqs(cfg))
        return prereqs
