"""Upgrade runbook generator.

Generates a Markdown runbook for upgrading a pattern from one platform version
to another. Driven entirely from the version registry — no full compose needed.

Usage (internal):
    from quickpat.compose.upgrade_generator import generate_upgrade_runbook
    path = generate_upgrade_runbook(spec, 'rhoai', '3.4', '3.5', Path('upgrade/'))

CLI:
    quickpat compose spec.yaml --target rhoai=3.4..3.5
"""

from datetime import date
from pathlib import Path

from .version_registry import resolve_version, get_breaking_changes
from ..operators import OPERATORS


def generate_upgrade_runbook(
    spec,
    platform: str,
    from_version: str,
    to_version: str,
    output_dir: Path,
    spec_dir: str = None,
) -> Path:
    """Generate an upgrade runbook and write it to output_dir.

    Returns the path of the written RUNBOOK.md.
    Raises ValueError for unknown platform/version or same-version input.
    Raises OSError if output_dir is a file rather than a directory.
    """
    if from_version == to_version:
        raise ValueError(
            f"from_version and to_version are both {from_version!r} — "
            f"specify two different versions (e.g. {platform}=3.4..3.5)"
        )
    from_data = resolve_version(platform, from_version)
    to_data = resolve_version(platform, to_version)
    breaking = get_breaking_changes(platform, from_version, to_version)
    sub_changes = _diff_subscriptions(from_data, to_data)
    dsc_changes = _diff_dsc(from_data, to_data)

    folder_name = f'{platform}-v{from_version}-to-v{to_version}'
    runbook_dir = output_dir / folder_name
    runbook_dir.mkdir(parents=True, exist_ok=True)
    runbook_path = runbook_dir / 'RUNBOOK.md'

    content = _render_runbook(
        spec=spec,
        platform=platform,
        from_version=from_version,
        to_version=to_version,
        breaking=breaking,
        sub_changes=sub_changes,
        dsc_changes=dsc_changes,
        from_data=from_data,
        to_data=to_data,
    )
    runbook_path.write_text(content, encoding='utf-8')
    return runbook_path


# ── Diff helpers ──────────────────────────────────────────────────────────────

def _diff_subscriptions(from_data: dict, to_data: dict) -> list:
    """Return operator subscription changes between two version entries."""
    changes = []
    from_ops = from_data.get('operators', {})
    to_ops = to_data.get('operators', {})
    all_keys = sorted(set(from_ops) | set(to_ops))

    for op_key in all_keys:
        from_op = from_ops.get(op_key, {})
        to_op = to_ops.get(op_key, {})
        if from_op == to_op:
            continue
        registry_entry = OPERATORS.get(op_key, {})
        changes.append({
            'op_key': op_key,
            'display_name': registry_entry.get('display_name', op_key),
            'from': from_op,
            'to': to_op,
            'is_new': op_key not in from_ops,
            'is_removed': op_key not in to_ops,
        })

    return changes


def _diff_dsc(from_data: dict, to_data: dict) -> list:
    """Return DSC component state changes between two version entries."""
    changes = []
    from_dsc = from_data.get('dsc_defaults', {})
    to_dsc = to_data.get('dsc_defaults', {})
    all_components = sorted(set(from_dsc) | set(to_dsc))

    for comp in all_components:
        from_state = from_dsc.get(comp)
        to_state = to_dsc.get(comp)
        if from_state == to_state:
            continue
        changes.append({
            'component': comp,
            'from': from_state or '(not present)',
            'to': to_state or '(not present)',
            'is_new': comp not in from_dsc,
            'is_removed': comp not in to_dsc,
        })

    return changes


# ── Runbook renderer ──────────────────────────────────────────────────────────

def _render_runbook(
    spec,
    platform: str,
    from_version: str,
    to_version: str,
    breaking: list,
    sub_changes: list,
    dsc_changes: list,
    from_data: dict,
    to_data: dict,
) -> str:
    lines = []
    today = str(date.today())
    platform_display = {'rhoai': 'Red Hat OpenShift AI (RHOAI)'}.get(platform, platform)
    blocking = [c for c in breaking if c.get('severity') == 'blocking']
    warnings = [c for c in breaking if c.get('severity') == 'warning']

    # ── Header ─────────────────────────────────────────────────────────────────
    lines += [
        f"# Upgrade Runbook: {platform.upper()} {from_version} → {to_version}",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Generated | {today} |",
        f"| Pattern | `{spec.name}` |",
        f"| Platform | {platform_display} |",
        f"| From version | {from_version} |",
        f"| To version | {to_version} |",
        f"| Blocking issues | {len(blocking)} |",
        f"| Subscription changes | {len(sub_changes)} |",
        f"| DSC component changes | {len(dsc_changes)} |",
        "",
        "> **Generated by `quickpat compose spec.yaml --target "
        f"{platform}={from_version}..{to_version}`**",
        "",
        "---",
        "",
    ]

    # ── Pre-upgrade checklist ──────────────────────────────────────────────────
    lines += [
        "## Pre-upgrade checklist",
        "",
    ]

    if blocking:
        lines += [
            "> ⛔ **Complete ALL blocking items before proceeding.**",
            "> Skipping these can result in a failed upgrade requiring manual rollback.",
            "",
        ]
        for i, change in enumerate(blocking, 1):
            lines += [
                f"### {i}. [BLOCKING] {change['description']}",
                "",
                f"**Action required:** {change['action']}",
                "",
            ]
            if change.get('docs'):
                lines += [f"**Documentation:** {change['docs']}", ""]
    elif warnings:
        lines.append("> ⚠️ No blocking changes, but review the warnings below.\n")
    else:
        lines.append("> ✅ No blocking pre-upgrade actions required for this version jump.\n")

    if warnings:
        lines.append("### Warnings\n")
        for change in warnings:
            lines += [
                f"- **{change['description']}**  ",
                f"  Action: {change['action']}",
                "",
            ]

    lines.append("---\n")

    # ── Subscription changes ────────────────────────────────────────────────────
    lines += ["## Subscription changes\n"]

    new_ops = [c for c in sub_changes if c['is_new']]
    removed_ops = [c for c in sub_changes if c['is_removed']]
    changed_ops = [c for c in sub_changes if not c['is_new'] and not c['is_removed']]

    if changed_ops:
        lines += [
            "### Channel and approval changes",
            "",
            "| Operator | Current channel | New channel | installPlanApproval |",
            "|---|---|---|---|",
        ]
        for c in changed_ops:
            from_ch = c['from'].get('channel', '(default)')
            to_ch = c['to'].get('channel', '(default)')
            approval = c['to'].get('installPlanApproval', 'Automatic')
            ch_display = f"{from_ch} → **{to_ch}**" if from_ch != to_ch else f"{to_ch} (unchanged)"
            lines.append(f"| {c['display_name']} | {from_ch} | {to_ch} | {approval} |")
        lines.append("")

        if any(c['to'].get('installPlanApproval') == 'Manual' for c in changed_ops):
            lines += [
                "> **Note:** `installPlanApproval: Manual` means the operator will **not**",
                "> auto-upgrade after the subscription channel is updated. You must approve",
                "> the InstallPlan in the OpenShift console or with:",
                "> ```bash",
                "> oc get installplan -n redhat-ods-operator",
                "> oc patch installplan <name> -n redhat-ods-operator --type merge \\",
                ">   -p '{\"spec\":{\"approved\":true}}'",
                "> ```",
                "",
            ]

    if new_ops:
        lines += [
            "### New operators added by this upgrade",
            "",
            "| Operator | Channel | Namespace |",
            "|---|---|---|",
        ]
        for c in new_ops:
            registry = OPERATORS.get(c['op_key'], {})
            ns = registry.get('namespace', '(see docs)')
            ch = c['to'].get('channel', registry.get('channel', 'stable'))
            lines.append(f"| {c['display_name']} | {ch} | `{ns}` |")
        lines.append("")

    if removed_ops:
        lines += ["### Operators removed by this upgrade\n"]
        for c in removed_ops:
            lines.append(f"- {c['display_name']} (`{c['op_key']}`)")
        lines.append("")

    if not sub_changes:
        lines.append("No subscription changes between these versions.\n")

    lines.append("---\n")

    # ── DSC component changes ──────────────────────────────────────────────────
    lines += ["## DataScienceCluster changes\n"]

    new_comps = [c for c in dsc_changes if c['is_new']]
    removed_comps = [c for c in dsc_changes if c['is_removed']]
    changed_comps = [c for c in dsc_changes if not c['is_new'] and not c['is_removed']]

    if changed_comps:
        lines += [
            "| Component | Current state | New state |",
            "|---|---|---|",
        ]
        for c in changed_comps:
            lines.append(f"| `{c['component']}` | {c['from']} | **{c['to']}** |")
        lines.append("")

    if new_comps:
        lines += ["### New DSC components in this version\n"]
        for c in new_comps:
            lines.append(f"- `{c['component']}`: {c['to']}")
        lines.append("")

    if removed_comps:
        lines += ["### DSC components removed in this version\n"]
        for c in removed_comps:
            lines.append(f"- `{c['component']}`: was {c['from']}")
        lines.append("")

    if not dsc_changes:
        lines.append("No DataScienceCluster component changes between these versions.\n")

    lines.append("---\n")

    # ── Upgrade procedure ──────────────────────────────────────────────────────
    lines += [
        "## Upgrade procedure",
        "",
        "### Step 1: Resolve blocking issues",
        "",
    ]
    if blocking:
        lines.append("Complete all blocking items listed in the pre-upgrade checklist above.\n")
    else:
        lines.append("No blocking issues — proceed to step 2.\n")

    lines += [
        "### Step 2: Regenerate the pattern",
        "",
        "Update the spec repo to target the new version and commit:",
        "",
        "```bash",
        f"# In the spec repo",
        f"quickpat compose spec.yaml --target {platform}={to_version}",
        f"quickpat compose spec.yaml --target {platform}={to_version} --format qs",
        "",
        "git add vp-out/ qs-out/",
        f'git commit -m "Upgrade to {platform_display} {to_version}"',
        "git push",
        "```",
        "",
        "Or pin the version in `spec.yaml` so future compose runs use it automatically:",
        "",
        "```yaml",
        "target:",
        f"  platform: {platform}",
        f"  version: \"{to_version}\"",
        "```",
        "",
        "### Step 3: Apply the new subscription channels",
        "",
        "ArgoCD will sync the updated `values-prod.yaml` and update the operator subscriptions.",
        "Watch the sync status:",
        "",
        "```bash",
        "oc get applications -n openshift-gitops",
        "```",
        "",
    ]

    if any(c['to'].get('installPlanApproval') == 'Manual' for c in sub_changes if not c['is_new']):
        lines += [
            "### Step 4: Approve InstallPlans",
            "",
            "Because `installPlanApproval: Manual` is set, approve the pending InstallPlans:",
            "",
            "```bash",
            f"oc get installplan -n redhat-ods-operator",
            f"# Approve each pending plan:",
            f"oc patch installplan <name> -n redhat-ods-operator --type merge \\",
            f"  -p '{{\"spec\":{{\"approved\":true}}}}'",
            "```",
            "",
        ]

    lines.append("---\n")

    # ── Verification ───────────────────────────────────────────────────────────
    lines += [
        "## Post-upgrade verification",
        "",
        "```bash",
        "# Verify the DSC is ready",
        "oc get datasciencecluster -o jsonpath='{.items[0].status.phase}'",
        "",
        "# Verify the RHOAI CSV version",
        "oc get csv -n redhat-ods-operator | grep rhods",
        "",
        "# Check no degraded components",
        "oc get datasciencecluster -o jsonpath='{.items[0].status.conditions}' | python3 -m json.tool",
        "```",
        "",
        "---",
        "",
        "*Generated by [QuickPat](https://github.com/atyronesmith/quickpat)*",
    ]

    return '\n'.join(lines) + '\n'
