"""Pattern generator: Helm charts."""

import re
import shutil
from pathlib import Path

from ..operators import INFRA_CHARTS

class ChartsGeneratorMixin:
    """Mixin for PatternGenerator."""

    def _apply_dsc_overrides(self, cr: dict, dsc_config: dict) -> dict:
        """Apply ai-platform-foundation block DSC component states to a CR dict."""
        if not dsc_config:
            return cr
        components = cr['spec']['components']
        for comp_name, state in dsc_config.items():
            if comp_name in components:
                components[comp_name]['managementState'] = state
            else:
                components[comp_name] = {'managementState': state}
        return cr

    def _apply_gpu_overrides(self, cr: dict, gpu_config: dict) -> dict:
        """Apply gpu-compute block config to a ClusterPolicy CR dict."""
        if not gpu_config:
            return cr
        spec = cr['spec']
        if 'mig_strategy' in gpu_config:
            spec['mig']['strategy'] = gpu_config['mig_strategy']
        if 'dcgm' in gpu_config:
            spec['dcgmExporter']['enabled'] = bool(gpu_config['dcgm'])
        if 'vgpu_manager' in gpu_config:
            spec['vgpuManager']['enabled'] = bool(gpu_config['vgpu_manager'])
        driver_cfg = gpu_config.get('driver', {})
        up = driver_cfg.get('upgrade_policy', {})
        if 'auto_upgrade' in up:
            spec['driver']['upgradePolicy']['autoUpgrade'] = bool(up['auto_upgrade'])
        return cr

    def _generate_infra_charts(self):
        import copy
        operators = self.config.get('operators', [])
        dsc_config = self.config.get('dsc_config', {})
        gpu_config = self.config.get('gpu_config', {})

        for op_key in operators:
            if op_key not in INFRA_CHARTS:
                continue
            ic = INFRA_CHARTS[op_key]
            chart_dir = self.output_dir / 'charts' / ic['chart_name']
            tmpl_dir = chart_dir / 'templates'
            tmpl_dir.mkdir(parents=True, exist_ok=True)

            self._write_yaml(chart_dir / 'Chart.yaml', {
                'apiVersion': 'v2',
                'name': ic['chart_name'],
                'description': ic['description'],
                'version': '0.1.0',
                'type': 'application',
            })

            self._write_yaml(chart_dir / 'values.yaml', {
                'global': {'pattern': ''},
            })

            cr = copy.deepcopy(ic['cr'])
            if op_key == 'openshift-ai':
                cr = self._apply_dsc_overrides(cr, dsc_config)
            elif op_key == 'nvidia-gpu':
                cr = self._apply_gpu_overrides(cr, gpu_config)

            self._write_yaml(tmpl_dir / ic['template_name'], cr)

    def _generate_custom_component_stubs(self):
        """Generate or copy charts for custom: components.

        If a hand-written chart exists in the application repo (detected via
        existing_custom_charts), copy it into the VP output. Otherwise generate
        a stub with documented values.yaml so the implementer knows what to fill in.
        """
        custom_components = self.config.get('custom_components', {})
        if not custom_components:
            return

        existing = self.config.get('existing_custom_charts', set())
        spec_dir = self.config.get('spec_dir')

        for comp_name, comp in custom_components.items():
            if getattr(comp, 'deploy', 'argocd') == 'manual':
                continue

            chart_dst = self.output_dir / 'charts' / comp_name

            if comp_name in existing and spec_dir:
                # Real chart exists in the application repo — copy it in.
                chart_src = Path(spec_dir) / 'charts' / comp_name
                self._copy_chart(chart_src, chart_dst)
                continue

            # No hand-written chart — generate a documented stub.
            tmpl_dir = chart_dst / 'templates'
            tmpl_dir.mkdir(parents=True, exist_ok=True)

            image = getattr(comp, 'image', '') or ''
            self._write_yaml(chart_dst / 'Chart.yaml', {
                'apiVersion': 'v2',
                'name': comp_name,
                'description': f'Custom component: {comp_name}',
                'version': '0.1.0',
                'type': 'application',
            })

            ports = getattr(comp, 'ports', []) or []
            env = getattr(comp, 'env', {}) or {}
            resources = getattr(comp, 'resources', {}) or {}
            values_lines = [
                '# Custom component stub — generated by quickpat compose',
                f'# Image: {image}',
                f'# Replicas: {getattr(comp, "replicas", 1)}',
            ]
            if ports:
                values_lines.append('# Ports:')
                for p in ports:
                    values_lines.append(f'#   {p}')
            if env:
                values_lines.append('# Env:')
                for k, v in env.items():
                    values_lines.append(f'#   {k}: {v}')
            if resources:
                values_lines.append(f'# Resources: {resources}')
            values_lines += ['', 'global:', '  pattern: ""']
            (chart_dst / 'values.yaml').write_text('\n'.join(values_lines) + '\n')
            (tmpl_dir / '.gitkeep').touch()
    @staticmethod
    def _eso_escape(value):
        """Wrap {{ .field }} refs in backticks so they survive Helm rendering."""
        return re.sub(r'\{\{\s*(\.\S+?)\s*\}\}', r'{{ `{{ \1 }}` }}', value)

    @staticmethod
    def _transform_computed_template(template, source_fields):
        """Convert Helm template syntax to ExternalSecret template syntax."""
        t = template
        t = re.sub(r'\|\s*b64enc', '', t)
        t = re.sub(r'\|\s*quote', '', t)
        t = t.strip()

        printf_m = re.match(
            r'\{\{\s*printf\s+"([^"]+)"\s*(.*?)\s*\}\}', t, re.DOTALL,
        )
        if printf_m:
            fmt_str = printf_m.group(1)
            args_str = printf_m.group(2).strip()
            # Parse args in order: field refs and include calls
            args = re.findall(
                r'\(include\s+"[^"]*"\s+\.\)|\.[\w][\w.-]*', args_str,
            )
            result = fmt_str
            for arg in args:
                if arg.startswith('(include'):
                    # Drop the include and its %s
                    result = result.replace('%s', '', 1)
                else:
                    # Extract the field name from .Values.secret.X or .X
                    field = re.sub(r'^\.(?:Values\.(?:[\w]+\.)*)?', '', arg)
                    result = result.replace('%s', '{{ .%s }}' % field, 1)
            result = re.sub(r'%[sdvfgq]', '', result)
            return result

        # Non-printf: replace .Values refs inline
        t = re.sub(r'\.Values\.(?:[\w]+\.)*(\w[\w-]*)', r'.\1', t)
        t = re.sub(r'\(include\s+"[^"]*"\s+\.\)', '', t)
        return t

    def _generate_pattern_secrets_chart(self):
        """Generate charts/{app-name}-secrets/ with ExternalSecret CRDs."""
        secret_groups = self.config.get('secret_groups', {})
        if not secret_groups:
            return

        app_name = self.config.get('app_name', self.analysis.name)
        secrets_chart_name = f"{app_name}-secrets"
        chart_dir = self.output_dir / 'charts' / secrets_chart_name
        chart_dir.mkdir(parents=True, exist_ok=True)
        tmpl_dir = chart_dir / 'templates'
        tmpl_dir.mkdir(exist_ok=True)

        pattern_name = self.config['pattern_name']
        self._write_yaml(chart_dir / 'Chart.yaml', {
            'apiVersion': 'v2',
            'name': secrets_chart_name,
            'version': '0.1.0',
            'description': f'ExternalSecret CRDs for {pattern_name}',
            'type': 'application',
        })

        secret_groups = self.config.get('secret_groups', {})
        vault_prefix = self.config.get('vault_prefix', 'hub')

        values_stubs = {
            'secretStore': {
                'name': 'vault-backend',
                'kind': 'ClusterSecretStore',
            },
        }
        for gn in secret_groups:
            values_stubs[gn] = {
                'key': f'secret/data/{vault_prefix}/{gn}',
                'refreshInterval': '2m0s',
            }
        self._write_yaml(chart_dir / 'values.yaml', values_stubs)
        secret_target_names = self.config.get('secret_target_names', {})

        for group_name, fields in secret_groups.items():
            target_name = secret_target_names.get(group_name, group_name)

            # Build per-key data entries and target template data
            data_entries = []
            template_data = {}
            for f in fields:
                fname = f['name']
                if f.get('computed'):
                    template_data[fname] = self._eso_escape(
                        self._transform_computed_template(
                            f['template'], f.get('source_fields', []),
                        ),
                    )
                else:
                    data_entries.append({
                        'secretKey': fname,
                        'remoteRef': {
                            'key': f'secret/data/{vault_prefix}/{group_name}',
                            'property': fname,
                        },
                    })
                    template_data[fname] = '{{ `{{ .%s }}` }}' % fname

            ext_secret = {
                'apiVersion': 'external-secrets.io/v1',
                'kind': 'ExternalSecret',
                'metadata': {'name': target_name},
                'spec': {
                    'refreshInterval': '2m0s',
                    'secretStoreRef': {
                        'name': 'vault-backend',
                        'kind': 'ClusterSecretStore',
                    },
                    'target': {
                        'name': target_name,
                        'template': {
                            'type': 'Opaque',
                            'engineVersion': 'v2',
                            'data': template_data,
                        },
                    },
                    'data': data_entries,
                },
            }

            filename = f'{group_name}-secret.yaml'
            self._write_yaml(tmpl_dir / filename, ext_secret)

    def _generate_app_override_file(self):
        """Generate overrides/<app-name>.yaml disabling in-chart secret creation."""
        override_entries = self.config.get('override_entries', [])
        if not override_entries:
            return

        overrides_dir = self.output_dir / 'overrides'
        overrides_dir.mkdir(exist_ok=True)

        # Build nested dict from dotted paths
        override_data = {}
        for entry in override_entries:
            parts = entry['path'].split('.')
            d = override_data
            for part in parts[:-1]:
                d = d.setdefault(part, {})
            d[parts[-1]] = entry['value']

        app_name = self.config.get('app_name', self.analysis.name)
        self._write_yaml(overrides_dir / f'{app_name}.yaml', override_data)

    # ── charts ──────────────────────────────────────────────────────

    def _copy_chart_locally(self):
        default_strategy = self.config.get('chart_strategy', 'remote')
        for ci in self.analysis.charts:
            strategy = ci.strategy or default_strategy
            if strategy != 'local':
                continue
            dest = self.output_dir / 'charts' / ci.name
            src = Path(ci.chart_path)

            if dest.exists():
                shutil.rmtree(dest)

            shutil.copytree(src, dest)
