"""Pattern generator: README, LICENSE, spec docs."""

from ..operators import OPERATORS
from .report import build_report


class DocsGeneratorMixin:
    """Mixin for PatternGenerator."""

    def _generate_license(self):
        content = (
            'Apache License\n'
            'Version 2.0, January 2004\n'
            'http://www.apache.org/licenses/\n'
            '\n'
            'TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n'
            '\n'
            'See http://www.apache.org/licenses/LICENSE-2.0 for full terms.\n'
        )
        (self.output_dir / 'LICENSE').write_text(content)

    def _generate_spec_docs(self):
        """Process and write spec docs: entries into the VP output directory.

        Runs after _generate_readme() so spec-authored docs overwrite the
        auto-generated README when target: README.md is declared.
        """
        from ..compose.doc_filter import process_docs
        process_docs(
            doc_entries=self.config.get('docs', []),
            spec_dir=self.config.get('spec_dir') or str(self.output_dir),
            output_dir=self.output_dir,
            deploy_mode='vp',
        )
    def _generate_readme(self):
        a = self.analysis
        name = self.config.get('pattern_name', a.name)
        repo_url = (self.config.get('git_repo_url', '') or a.git_repo_url).removesuffix('.git')
        lines = [f'# {name}', '']

        # Boilerplate — what this repo is
        source_link = f'[{a.name}]({repo_url})' if repo_url else a.name
        lines.append(
            f'> This is a [Validated Pattern](https://validatedpatterns.io/) generated by '
            f'[QuickPat](https://github.com/atyronesmith/quickpat) from the '
            f'{source_link} AI Quickstart.'
        )
        lines.append('')

        # About the quickstart
        description = a.description if a.description != 'A Helm chart for Kubernetes' else ''
        if description or repo_url:
            lines.append('## About the Quickstart')
            lines.append('')
            if description:
                lines.append(description)
                lines.append('')
            if repo_url:
                lines.append(
                    f'For full details, see the '
                    f'[original quickstart README]({repo_url}#readme).'
                )
                lines.append('')

        # What the pattern provides
        lines.append('## What This Pattern Provides')
        lines.append('')
        lines.append('- GitOps deployment via ArgoCD')
        if a.detected_operators:
            op_names = [
                OPERATORS[op]['display_name']
                for op in a.detected_operators if op in OPERATORS
            ]
            if op_names:
                lines.append(f'- Operator lifecycle management ({", ".join(op_names)})')
        lines.append('- HashiCorp Vault secret management')
        lines.append('- Multi-cloud support (AWS, Azure, GCP, IBM Cloud)')
        lines.append('')

        # Deploy
        lines.append('## Deploy')
        lines.append('')
        lines.append('```bash')
        lines.append('# Clone and deploy')
        lines.append('oc login <cluster>')
        lines.append('./pattern.sh make install')
        lines.append('```')
        lines.append('')
        lines.append(
            'The pattern must be on a git remote accessible by the cluster. '
            'If starting from a local copy, push it to a git repo first.'
        )
        lines.append('')

        # Directory structure
        lines.append('## Directory Structure')
        lines.append('')
        lines.append('```')
        lines.append('values-global.yaml          # Global config, multisource settings')
        gn = self.config.get('cluster_group_name', 'prod')
        pad = ' ' * max(1, 28 - len(f'values-{gn}.yaml'))
        lines.append(f'values-{gn}.yaml{pad}# Cluster group: namespaces, operators, apps')
        lines.append('values-secret.yaml.template # Vault secrets template')
        lines.append('Makefile                    # Build targets')
        lines.append('pattern.sh                  # VP utility container runner')
        lines.append('charts/                     # Helm chart(s)')
        lines.append('overrides/                  # Platform-specific value overrides')
        if self.config.get('generate_crc_scripts', False):
            lines.append('scripts/                    # CRC deploy, undeploy, validate, status')
        lines.append('docs/                       # Quickstart analysis report')
        lines.append('```')
        lines.append('')

        # Footer
        lines.append('## Documentation')
        lines.append('')
        lines.append(
            'See [`docs/quickstart-analysis.md`](docs/quickstart-analysis.md) '
            'for detailed analysis of the original quickstart.'
        )
        lines.append('')

        (self.output_dir / 'README.md').write_text('\n'.join(lines))

    # ── docs report ─────────────────────────────────────────────────

    def _generate_report(self):
        docs_dir = self.output_dir / 'docs'
        docs_dir.mkdir(exist_ok=True)
        report = build_report(self.analysis, self.config)
        (docs_dir / 'quickstart-analysis.md').write_text(report)
