"""Generates Validated Pattern files from quickstart analysis."""

from pathlib import Path

import yaml

from ..analyzer import QuickstartAnalysis
from .charts import ChartsGeneratorMixin
from .docs import DocsGeneratorMixin
from .overrides import OverridesGeneratorMixin
from .scaffolding import ScaffoldingGeneratorMixin
from .scripts import ScriptsGeneratorMixin
from .values import ValuesGeneratorMixin


class PatternGenerator(
    ValuesGeneratorMixin,
    ScaffoldingGeneratorMixin,
    ChartsGeneratorMixin,
    OverridesGeneratorMixin,
    DocsGeneratorMixin,
    ScriptsGeneratorMixin,
):
    """Generates a complete Validated Pattern directory structure."""

    def __init__(self, analysis: QuickstartAnalysis, config: dict):
        self.analysis = analysis
        self.config = config
        self.output_dir = Path(config['output_dir']).resolve()
        self.warnings: list = []

    def generate(self):
        """Generate all pattern files."""
        self.warnings = []
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self._generate_values_global()
        self._generate_values_hub()
        self._generate_values_secret_template()
        self._generate_makefile()
        self._generate_makefile_common()
        self._generate_pattern_sh()
        self._generate_pattern_metadata()
        self._generate_ansible_cfg()
        self._generate_ansible_lint()
        self._generate_gitignore()
        self._generate_overrides()
        self._generate_infra_charts()
        self._generate_custom_component_stubs()
        if self.config.get('generate_crc_scripts', False):
            self._generate_scripts()
        self._generate_readme()
        self._generate_report()
        self._generate_license()
        self._generate_spec_docs()

        default_strategy = self.config.get('chart_strategy', 'remote')
        has_local = any(
            (ci.strategy or default_strategy) == 'local'
            for ci in self.analysis.charts
        )
        if has_local:
            self._copy_chart_locally()

        has_remote = any(
            (ci.strategy or default_strategy) == 'remote'
            for ci in self.analysis.charts
        )
        if has_remote and self.config.get('use_vault'):
            self._generate_pattern_secrets_chart()
            self._generate_app_override_file()

    def _write_yaml(self, path, data, doc_start=False):
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w') as f:
            if self.config.get('generated_headers'):
                f.write('# Generated by quickpat compose — do not edit\n')
            if doc_start:
                f.write('---\n')
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)

    def _copy_chart(self, src: Path, dst: Path):
        """Copy a hand-written chart directory into the VP output.

        Replaces any previous copy so re-runs stay in sync with the source.
        The source is always the hand-written chart in the application repo;
        the destination is charts/<name>/ inside the VP output directory.
        """
        import shutil
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
