"""Pattern generator: scaffolding files."""

from datetime import date

from .. import __version__

class ScaffoldingGeneratorMixin:
    """Mixin for PatternGenerator."""

    def _generate_makefile(self):
        content = (
            "# Generated by quickpat\n"
            "# Add custom targets above or below the include line\n"
            "\n"
            "include Makefile-common\n"
        )
        (self.output_dir / 'Makefile').write_text(content)

    def _generate_makefile_common(self):
        content = (
            'MAKEFLAGS += --no-print-directory\n'
            'ANSIBLE_STDOUT_CALLBACK ?= rhvp.cluster_utils.readable\n'
            'ANSIBLE_RUN ?= ANSIBLE_STDOUT_CALLBACK='
            '$(ANSIBLE_STDOUT_CALLBACK) ansible-playbook '
            '$(EXTRA_PLAYBOOK_OPTS)\n'
            '\n'
            '.PHONY: help\n'
            'help: ## Print this help message\n'
            '\t@echo "Documentation: https://validatedpatterns.io/"\n'
            '\t@awk \'BEGIN {FS = ":.*##"; printf "\\nUsage:\\n'
            '  make \\033[36m<target>\\033[0m\\n"} '
            '/^(\\s|[a-zA-Z_0-9-])+:.*?##/ '
            '{ printf "  \\033[36m%-35s\\033[0m %s\\n", $$1, $$2 } '
            '/^##@/ { printf "\\n\\033[1m%s\\033[0m\\n", '
            'substr($$0, 5) } \' $(MAKEFILE_LIST)\n'
            '\n'
            '##@ Pattern Install Tasks\n'
            '.PHONY: show\n'
            'show: ## Shows the template that would be applied by the \'make install\' target\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.show\n'
            '\n'
            '.PHONY: operator-deploy\n'
            'operator-deploy operator-upgrade: '
            '## Installs/updates the pattern on a cluster (DOES NOT load secrets)\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.operator_deploy\n'
            '\n'
            '.PHONY: install\n'
            'install: pattern-install '
            '## Installs the pattern onto a cluster\n'
            '\n'
            '.PHONY: uninstall\n'
            'uninstall: ## Uninstall the pattern (EXPERIMENTAL)\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.uninstall\n'
            '\n'
            '.PHONY: pattern-install\n'
            'pattern-install:\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.install\n'
            '\n'
            '.PHONY: load-secrets\n'
            'load-secrets: ## Loads secrets onto the cluster (unless explicitly disabled in values-global.yaml)\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.load_secrets\n'
            '\n'
            '##@ Validation Tasks\n'
            '.PHONY: validate-prereq\n'
            'validate-prereq: ## Verify pre-requisites\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.validate_prereq\n'
            '\n'
            '.PHONY: validate-origin\n'
            'validate-origin: ## Verify the git origin is available\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.validate_origin\n'
            '\n'
            '.PHONY: validate-cluster\n'
            'validate-cluster: ## Do cluster validations before install\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.validate_cluster\n'
            '\n'
            '.PHONY: validate-schema\n'
            'validate-schema: ## Validates values files against schema\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.validate_schema\n'
            '\n'
            '.PHONY: argo-healthcheck\n'
            'argo-healthcheck: ## Checks if all argo apps are synced\n'
            '\t@$(ANSIBLE_RUN) rhvp.cluster_utils.argo_healthcheck\n'
        )
        (self.output_dir / 'Makefile-common').write_text(content)

    # ── pattern.sh ──────────────────────────────────────────────────

    def _generate_pattern_sh(self):
        # Standard utility container runner, identical across all patterns
        content = r'''#!/bin/bash
set -euo pipefail

function is_available {
  command -v "$1" >/dev/null 2>&1 || { echo >&2 "$1 is required but it's not installed. Aborting."; exit 1; }
}

function version {
    echo "$1" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
}

if [ -z "${PATTERN_UTILITY_CONTAINER:-}" ]; then
    PATTERN_UTILITY_CONTAINER="quay.io/validatedpatterns/utility-container"
fi
if [ -n "${PATTERN_DISCONNECTED_HOME:-}" ]; then
    PATTERN_UTILITY_CONTAINER="${PATTERN_DISCONNECTED_HOME}/utility-container"
    PATTERN_INSTALL_CHART="oci://${PATTERN_DISCONNECTED_HOME}/pattern-install"
    echo "PATTERN_DISCONNECTED_HOME is set to ${PATTERN_DISCONNECTED_HOME}"
    echo "Setting the following variables:"
    echo "  PATTERN_UTILITY_CONTAINER: ${PATTERN_UTILITY_CONTAINER}"
    echo "  PATTERN_INSTALL_CHART: ${PATTERN_INSTALL_CHART}"
fi

readonly commands=(podman)
for cmd in "${commands[@]}"; do is_available "$cmd"; done

UNSUPPORTED_PODMAN_VERSIONS="1.6 1.5"
PODMAN_VERSION_STR=$(podman --version) || { echo "Failed to get podman version"; exit 1; }
for i in ${UNSUPPORTED_PODMAN_VERSIONS}; do
    if echo "${PODMAN_VERSION_STR}" | grep -q -E "\b${i}"; then
        echo "Unsupported podman version. We recommend > 4.3.0"
        podman --version
        exit 1
    fi
done

PODMAN_VERSION=$(echo "${PODMAN_VERSION_STR}" | awk '{ print $NF }')

PODMAN_ARGS=()
if [ "$(version "${PODMAN_VERSION}")" -lt "$(version "4.3.0")" ]; then
    PODMAN_ARGS=(-v "${HOME}:/root")
else
    MYNAME=$(id -n -u)
    MYUID=$(id -u)
    MYGID=$(id -g)
    PODMAN_ARGS=(--passwd-entry "${MYNAME}:x:${MYUID}:${MYGID}::/pattern-home:/bin/bash" --user "${MYUID}:${MYGID}" --userns "keep-id:uid=${MYUID},gid=${MYGID}")
fi

if [ -n "${KUBECONFIG:-}" ]; then
    if [[ ! "${KUBECONFIG}" =~ ^"${HOME}" ]]; then
        echo "${KUBECONFIG} is pointing outside of the HOME folder, this will make it unavailable from the container."
        echo "Please move it somewhere inside your $HOME folder, as that is what gets bind-mounted inside the container"
        exit 1
    fi
fi

REMOTE_PODMAN=$(podman system connection list | tail -n +2 | wc -l) || REMOTE_PODMAN=0
PKI_HOST_MOUNT_ARGS=()
if [ "${REMOTE_PODMAN}" -eq 0 ]; then
    if [ -d /etc/pki/tls ]; then
        PKI_HOST_MOUNT_ARGS=(-v /etc/pki:/etc/pki:ro)
    elif [ -d /etc/ssl ]; then
        PKI_HOST_MOUNT_ARGS=(-v /etc/ssl:/etc/ssl:ro)
    else
        PKI_HOST_MOUNT_ARGS=(-v /usr/share/ca-certificates:/usr/share/ca-certificates:ro)
    fi
fi

EXTRA_ARGS_ARRAY=()
if [ -n "${EXTRA_ARGS:-}" ]; then
    # shellcheck disable=SC2206
    EXTRA_ARGS_ARRAY=(${EXTRA_ARGS})
fi

podman run -it --rm --pull=newer \
    --security-opt label=disable \
    -e ANSIBLE_STDOUT_CALLBACK \
    -e DISABLE_VALIDATE_ORIGIN \
    -e EXTRA_HELM_OPTS \
    -e EXTRA_PLAYBOOK_OPTS \
    -e K8S_AUTH_HOST \
    -e K8S_AUTH_PASSWORD \
    -e K8S_AUTH_SSL_CA_CERT \
    -e K8S_AUTH_TOKEN \
    -e K8S_AUTH_USERNAME \
    -e K8S_AUTH_VERIFY_SSL \
    -e KUBECONFIG \
    -e PATTERN_DIR \
    -e PATTERN_DISCONNECTED_HOME \
    -e PATTERN_INSTALL_CHART \
    -e PATTERN_NAME \
    -e TARGET_BRANCH \
    -e TARGET_CLUSTERGROUP \
    -e TARGET_VARIANT \
    -e TARGET_ORIGIN \
    -e TOKEN_NAMESPACE \
    -e TOKEN_SECRET \
    -e UUID_FILE \
    -e VALUES_SECRET \
    "${PKI_HOST_MOUNT_ARGS[@]}" \
    -v "$(pwd -P)":"$(pwd -P)" \
    -v "${HOME}":"${HOME}" \
    -v "${HOME}":/pattern-home \
    "${PODMAN_ARGS[@]}" \
    "${EXTRA_ARGS_ARRAY[@]}" \
    -w "$(pwd -P)" \
    "$PATTERN_UTILITY_CONTAINER" \
    "$@"
'''
        script_path = self.output_dir / 'pattern.sh'
        script_path.write_text(content)
        script_path.chmod(0o755)

    # ── pattern-metadata.yaml ───────────────────────────────────────

    def _generate_pattern_metadata(self):
        pattern_name = self.config['pattern_name']
        display_name = pattern_name.replace('-', ' ').title()

        data = {
            'metadata_version': '2.0',
            'name': pattern_name,
            'pattern_version': '1.0',
            'display_name': display_name,
            'tier': self.config.get('tier', 'sandbox'),
            'quickpat': self._build_provenance(),
        }
        self._write_yaml(self.output_dir / 'pattern-metadata.yaml', data)

    def _build_provenance(self):
        """Build generation provenance for pattern-metadata.yaml."""
        prov = {
            'version': __version__,
            'generated': str(date.today()),
            'strategy': self.config.get('chart_strategy', 'remote'),
            'vault': bool(self.config.get('use_vault')),
        }

        source_url = self.config.get('git_repo_url')
        if source_url:
            prov['source'] = {
                'repo': source_url,
                'path': self.config.get('chart_path_in_repo', ''),
                'branch': self.config.get('chart_branch', 'main'),
            }

        ops = self.config.get('operators', [])
        if ops:
            prov['operators'] = sorted(ops)

        sg = self.config.get('secret_groups', {})
        if sg:
            prov['secret_groups'] = sorted(sg.keys())

        ig = self.config.get('ignore_differences')
        if ig:
            prov['ignore_differences'] = ig

        return prov

    # ── ansible.cfg ─────────────────────────────────────────────────

    def _generate_ansible_cfg(self):
        content = (
            '[defaults]\n'
            'localhost_warning=False\n'
            'retry_files_enabled=False\n'
            'interpreter_python=auto_silent\n'
            'timeout=30\n'
            'library=~/.ansible/plugins/modules'
            ':./ansible/plugins/modules'
            ':/usr/share/ansible/plugins/modules\n'
            'roles_path=~/.ansible/roles'
            ':./ansible/roles'
            ':/usr/share/ansible/roles'
            ':/etc/ansible/roles\n'
            'filter_plugins=~/.ansible/plugins/filter'
            ':./ansible/plugins/filter'
            ':/usr/share/ansible/plugins/filter\n'
            'collections_path=/usr/share/ansible/collections\n'
            '\n'
            '[inventory]\n'
            'inventory_unparsed_warning=False\n'
        )
        (self.output_dir / 'ansible.cfg').write_text(content)

    def _generate_ansible_lint(self):
        (self.output_dir / '.ansible-lint').write_text('')

    # ── .gitignore ──────────────────────────────────────────────────

    def _generate_gitignore(self):
        content = (
            '*~\n'
            '*.swp\n'
            '*.swo\n'
            'values-secret.yaml\n'
            '!values-secret.yaml.template\n'
            '.*.expected.yaml\n'
            'pattern-vault.init\n'
            'vault.init\n'
            'super-linter.log\n'
        )
        (self.output_dir / '.gitignore').write_text(content)
