"""Publish a generated vp-out/ tree to an immutable, versioned git tag.

The Validated Patterns Operator's Pattern CRD (gitops.hybrid-cloud-patterns.io/v1alpha1)
has no field for a subdirectory path within its target git repo -- it always clones the
whole repo and expects values-global.yaml, values-prod.yaml, Makefile, pattern.sh, and
charts/ at the repo root. QuickPat's one-repo-both-paths layout nests all of that under
vp-out/, so a live Pattern CR's ongoing GitOps reconciliation can never find its values
files there.

This module publishes vp-out/'s *already-committed* content to an immutable tag
(vp-v1, vp-v2, ...) whose tree sits at the tag's own root -- no subtree, no worktree
checkout, no copying. `git rev-parse HEAD:<vp-out>` already resolves to a tree object
whose entries are vp-out/'s direct children; feeding that tree straight into
`git commit-tree` publishes it at repo root for free, and correctly excludes anything
.gitignore'd (it was never part of the committed tree to begin with).

Each publish's commit is parented to the previous published tag's commit (not to
main's history), so any two published versions can be diffed directly:
    git diff vp-v3 vp-v7

The next version number is derived from the remote's existing vp-v* tags, never from
local state -- pattern-metadata.yaml is fully regenerated by every `compose` run and
would silently clobber a stored counter.

Repointing a live Pattern CR at a newly published tag is a deliberate, separate action
(an `oc patch` command is suggested, never executed by this module).
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

import yaml

_TAG_RE_TEMPLATE = r'refs/tags/{prefix}(\d+)$'


class PublishError(Exception):
    """Raised for conditions that should stop publishing before anything is written."""


@dataclass
class PublishResult:
    success: bool
    no_op: bool = False
    version: int | None = None
    tag: str = ''
    parent_tag: str = ''
    commit: str = ''
    tree: str = ''
    remote: str = ''
    pushed: bool = False
    dry_run: bool = False
    oc_patch_cmd: str = ''
    warnings: list = field(default_factory=list)


def _git(args, cwd, check=True, capture=True, timeout=30):
    """Run a git command, in the style of quickpat.clone.cloned_repo() / analyzer.detect_git_origin()."""
    return subprocess.run(
        ['git', *args],
        cwd=str(cwd),
        capture_output=capture,
        text=True,
        timeout=timeout,
        check=check,
    )


def _repo_root(path: Path) -> Path:
    try:
        result = _git(['rev-parse', '--show-toplevel'], cwd=path)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise PublishError(f"{path} is not inside a git repository") from e
    return Path(result.stdout.strip())


def _vp_out_relpath(repo_root: Path, vp_out_dir: Path) -> str:
    return vp_out_dir.resolve().relative_to(repo_root.resolve()).as_posix()


def _resolve_remote(repo_root: Path, remote: str, repo_url: str | None) -> str:
    if repo_url:
        return repo_url
    try:
        result = _git(['remote', 'get-url', remote], cwd=repo_root)
    except subprocess.CalledProcessError as e:
        raise PublishError(
            f"No git remote '{remote}' configured; configure one or pass --repo-url"
        ) from e
    url = result.stdout.strip()
    if not url:
        raise PublishError(
            f"No git remote '{remote}' configured; configure one or pass --repo-url"
        )
    return url


def _committed_tree_sha(repo_root: Path, rel: str) -> str:
    try:
        result = _git(['rev-parse', '--verify', f'HEAD:{rel}'], cwd=repo_root)
    except subprocess.CalledProcessError as e:
        raise PublishError(
            f"{rel} is not committed; run compose, review, and commit it before "
            "publishing (or pass --allow-dirty)"
        ) from e
    return result.stdout.strip()


def _dirty_tree_from_disk(repo_root: Path, vp_out_dir: Path) -> str:
    """Build a tree object from vp-out/'s on-disk content via a scratch index.

    Used only with --allow-dirty. Respects .gitignore since `git add -A` does.
    """
    import shutil
    import tempfile

    # The index file must not exist yet -- git initializes a fresh index at
    # this path. A pre-created (e.g. zero-byte) file is an invalid index.
    tmpdir = tempfile.mkdtemp(prefix='quickpat-publish-index-')
    try:
        index_path = str(Path(tmpdir) / 'index')
        env = _env_with(GIT_INDEX_FILE=index_path)
        subprocess.run(
            ['git', '--git-dir', str(repo_root / '.git'), '--work-tree', str(vp_out_dir),
             'add', '-A'],
            cwd=str(vp_out_dir), env=env, check=True, capture_output=True, text=True,
        )
        result = subprocess.run(
            ['git', '--git-dir', str(repo_root / '.git'), 'write-tree'],
            cwd=str(vp_out_dir), env=env, check=True, capture_output=True, text=True,
        )
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
    return result.stdout.strip()


def _env_with(**overrides):
    import os
    env = dict(os.environ)
    env.update(overrides)
    return env


def _vp_out_is_clean(repo_root: Path, rel: str) -> bool:
    diff = _git(['diff', '--quiet', 'HEAD', '--', rel], cwd=repo_root, check=False)
    if diff.returncode != 0:
        return False
    untracked = _git(
        ['ls-files', '--others', '--exclude-standard', '--', rel], cwd=repo_root
    )
    return untracked.stdout.strip() == ''


def _remote_versions(repo_root: Path, target: str, tag_prefix: str) -> list:
    result = _git(['ls-remote', '--tags', target, f'{tag_prefix}*'], cwd=repo_root)
    pattern = re.compile(_TAG_RE_TEMPLATE.format(prefix=re.escape(tag_prefix)))
    versions = []
    for line in result.stdout.splitlines():
        parts = line.split('\t', 1)
        if len(parts) != 2:
            continue
        ref = parts[1]
        if ref.endswith('^{}'):
            continue  # peeled annotated-tag entry, same version as its unpeeled ref
        m = pattern.search(ref)
        if m:
            versions.append(int(m.group(1)))
    return versions


def _fetch_tag(repo_root: Path, target: str, tag: str) -> None:
    try:
        _git(['fetch', target, f'refs/tags/{tag}:refs/tags/{tag}'], cwd=repo_root)
    except subprocess.CalledProcessError as e:
        raise PublishError(
            f"could not fetch parent tag {tag} from {target}: {e.stderr}"
        ) from e


def _tree_of_tag(repo_root: Path, tag: str) -> str:
    return _git(['rev-parse', f'{tag}^{{tree}}'], cwd=repo_root).stdout.strip()


def _commit_of_tag(repo_root: Path, tag: str) -> str:
    return _git(['rev-parse', f'{tag}^{{commit}}'], cwd=repo_root).stdout.strip()


def _commit_tree(repo_root: Path, tree: str, parent: str | None, message: str) -> str:
    args = ['commit-tree', tree, '-m', message]
    if parent:
        args = ['commit-tree', tree, '-p', parent, '-m', message]
    return _git(args, cwd=repo_root).stdout.strip()


def _create_tag(repo_root: Path, tag: str, commit: str, message: str) -> None:
    existing = _git(['tag', '-l', tag], cwd=repo_root).stdout.strip()
    if existing:
        # Leftover from a previously-failed push -- the remote is the source of
        # truth for the next version number, so replace rather than abort.
        _git(['tag', '-d', tag], cwd=repo_root)
    _git(['tag', '-a', tag, commit, '-m', message], cwd=repo_root)


def _push_tag(repo_root: Path, target: str, tag: str) -> None:
    try:
        _git(['push', target, f'refs/tags/{tag}'], cwd=repo_root)
    except subprocess.CalledProcessError as e:
        _git(['tag', '-d', tag], cwd=repo_root, check=False)
        raise PublishError(f"failed to push tag {tag} to {target}: {e.stderr}") from e


def _read_pattern_name(vp_out_dir: Path) -> str | None:
    metadata_path = vp_out_dir / 'pattern-metadata.yaml'
    if not metadata_path.exists():
        return None
    try:
        data = yaml.safe_load(metadata_path.read_text())
    except Exception:
        return None
    return (data or {}).get('name')


def _oc_patch_cmd(pattern_name: str, namespace: str, tag: str) -> str:
    return (
        f"oc patch pattern {pattern_name} -n {namespace} --type merge "
        f'-p \'{{"spec":{{"gitSpec":{{"targetRevision":"{tag}"}}}}}}\''
    )


def publish_vp(
    vp_out_dir: str,
    remote: str = 'origin',
    repo_url: str | None = None,
    tag_prefix: str = 'vp-v',
    message: str | None = None,
    pattern_name: str | None = None,
    namespace: str = 'patterns-operator',
    dry_run: bool = False,
    allow_dirty: bool = False,
) -> PublishResult:
    warnings = []
    vp_out_path = Path(vp_out_dir)
    if not vp_out_path.is_dir():
        raise PublishError(f"vp-out not found: {vp_out_dir}")

    repo_root = _repo_root(vp_out_path)
    rel = _vp_out_relpath(repo_root, vp_out_path)
    target = _resolve_remote(repo_root, remote, repo_url)

    if allow_dirty:
        tree = _dirty_tree_from_disk(repo_root, vp_out_path)
    else:
        if not _vp_out_is_clean(repo_root, rel):
            raise PublishError(
                f"{rel} has uncommitted changes; commit them first "
                "(or pass --allow-dirty)"
            )
        tree = _committed_tree_sha(repo_root, rel)

    versions = _remote_versions(repo_root, target, tag_prefix)
    n = max(versions, default=0) + 1
    tag = f'{tag_prefix}{n}'
    parent_tag = f'{tag_prefix}{n - 1}' if n > 1 else ''

    resolved_pattern_name = pattern_name or _read_pattern_name(vp_out_path) or Path(repo_root).name
    oc_cmd = _oc_patch_cmd(resolved_pattern_name, namespace, tag)
    default_message = f'Publish {tag} — Validated Pattern output at repo root'
    commit_message = message or default_message

    parent_commit = None
    if parent_tag:
        _fetch_tag(repo_root, target, parent_tag)
        prev_tree = _tree_of_tag(repo_root, parent_tag)
        if prev_tree == tree:
            return PublishResult(
                success=True, no_op=True, version=n - 1, tag=parent_tag,
                tree=tree, remote=target, warnings=warnings,
            )
        parent_commit = _commit_of_tag(repo_root, parent_tag)

    if dry_run:
        return PublishResult(
            success=True, dry_run=True, version=n, tag=tag, parent_tag=parent_tag,
            tree=tree, remote=target, oc_patch_cmd=oc_cmd, warnings=warnings,
        )

    commit = _commit_tree(repo_root, tree, parent_commit, commit_message)
    _create_tag(repo_root, tag, commit, commit_message)
    _push_tag(repo_root, target, tag)

    return PublishResult(
        success=True, version=n, tag=tag, parent_tag=parent_tag, commit=commit,
        tree=tree, remote=target, pushed=True, oc_patch_cmd=oc_cmd, warnings=warnings,
    )
